ranger/config/commands.py
Because the file extension for ".python_history" is not "python_history".
=> renameConsole -> rename_append + special cases for hidden files and directories

ranger/ext/direction.py
This allows to loop on a file list, going at the other side of the list when trying to go beyond the boundaries (e.g. pressing down when the last file is selected). 
Test command: `move up=1 cycle=true`
Note: in `minimum + pos % (maximum + offset - minimum)`, I am not sure if the use of 'offset' is appropriate (i.e. not sure whether it is broken or not).
=> Add a 'cycle' option to direction

ranger/core/metadata.py
In the case of a file with empty metadata, ranger was storing a key-value pair with an empty value. Now it removes the entire empty entry from `.metadata.json`.
=> Removal of empty metadata entries

ranger/config/rifle.conf
I think if someone has sxiv, feh or mirage installed, it should have a higher priority than eog or eom, because they are normally automatically installed along with mate or gnome.
it fits the philosophy of browser or documents default priority.
=> Priority change

ranger/config/rifle.conf
This patch fixes 2 problems at once in the default config, which prevent one
from editing files when his $EDITOR variable is set to "emacs -nw":
- $EDITOR variables consisting of "program name + options" are not handled
correctly because of quotes around $EDITOR. As a result, if $EDITOR is not
a simple program name (i.e. if it includes options, as in "emacs -nw"), the
full string is taken as a program and fails to run.
Error message: (/bin/sh: 1: emacs -nw: not found)
Removing quotes fixes this problem.
- emacs does not seems to handle the "--" correctly: it does not open any file
when it is there. I don't know why it is there, but removing it does not
prevent other editors (vim, nano) to run correctly, and makes emacs work.
=> Fix bugs when $EDITOR="emacs -nw"

ranger/config/commands.py, ranger/core/actions.py
Closes #97
When renaming a file, the internal file pointer will be set to the new
file name without checking if the file actually got renamed. This would
cause the file pointer to be set to an invalid file if renaming failed
because of bad privileges. With no valid file, the previev window will
disappear. This patch adds a return value to the core renaming method so
it can be checking by the caller. The rename command now checks if the
rename succeeded and only then sets the new file pointer.
=> Fix renaming with insufficient privileges

ranger/core/actions.py
If user deletes a file with an associated cached image preview (via scope.sh), ranger used to check this now non-existent file's modification time and crash in the process. I've added a check whether a file still exists.
=> Deleting a file with a cached image preview no longer crashes ranger

ranger/config/rc.conf
Fixed comment concerning default value of confirm_on_delete in rc.conf.
Issue #260
=> updated comment to reflect current default value for confirm_on_delete

ranger/config/commands.py, ranger/container/directory.py, ranger/container/fsobject.py, ranger/core/actions.py, ranger/gui/widgets/browsercolumn.py, ranger/gui/widgets/titlebar.py
The `%f`, `%s` and `%t` file macros used to return only the file basename, even if it was not located in the current directory. It would break the `%d/%f` idiom and many others when `:flat` was enabled. Now they return a path relative to the current directory (which is the same as the basename when `:flat` is disabled).
Additionally, I've renamed the fsobject.drawn_basename to fsobject.relative_path according to the discussion on the #ranger IRC channel and used it wherever possible.
=> Fixed the file macros with :flat enabled

doc/ranger.pod, ranger/api/__init__.py, ranger/config/commands.py, ranger/container/fsobject.py, ranger/core/actions.py, ranger/core/linemode.py, ranger/gui/widgets/browsercolumn.py
I have moved most of the linemode logic into a separate module and added a simple API to allow creating the custom linemodes. The abstract base class was used to catch as many errors as possible as soon as possible -- most of the implementations will be supplied by the users.
=> Linemode API added to make the custom linemodes possible

ranger/config/commands.py
s/self\.notify/self\.fm\.notify/
=> Fix a typo s/self\.notify/self\.fm\.notify/

ranger/core/actions.py
```
'module' object has no attribute 'mkdirs'
```
https://docs.python.org/2/library/os.html?highlight=makedirs#os.makedirs
https://docs.python.org/3/library/os.html?highlight=makedirs#os.makedirs
ranger is best file manager! Thanks.
=> os module does not have "mkdirs" function 

ranger/config/commands.py, ranger/container/fsobject.py
Added tab complete functionality for colorschemes under the :set command.
Will cycle through all availble colorschemes (under ranger/colorschemes) when no colorscheme is specified; and will tab complete if an incomplete colorscheme name is specified
Fixes #244
=> added tab complete functionality for :set colorschemes

ranger.py
Previously, $tempfile (namely, /tmp/chosendir) was not cleaned up correctly when the ranger process quit in `pwd` without moving to other directory.  This causes permission errors in multi-user environments trying to overwrite $tempfile created by a different user.
This commit solves the problem in two ways:
- Correctly clean up temporary files
- Avoid writing to the same temporary by using mktemp(1)
=> ranger.py: fixed issues with $tempfile in embedded shell

examples/bash_automatic_cd.sh, ranger.py
mktemp on Mac OS X (and probably all BSDs) just returns an error when
invoked without any arguments.  The -t option used in this change is
interpreted differently on Mac OS X and Linux, and is deprecated on
Linux, but this invocation works as expected on both.
See discussion at https://unix.stackexchange.com/questions/30091
Another alternative would be to use Python's tempfile module:
https://docs.python.org/2/library/tempfile.html
=> Fix mktemp invocation to work on Mac OS X and Linux

ranger/container/bookmarks.py
Proposed fix for the (non-)bug #59, where the owner of the bookmarks file is changed to root when running ranger as root but with a user's environment. This could be called user error, but this patch will hopefully prevent further confusion such as #267. 
The try-except statement catches the (weird) case where the file is already owned by another user. 
Should this also be applied to other files managed by ranger?
=> preserve permissions when updating bookmarks. Fix for #59

ranger/ext/img_display.py
This small changes make the previewed image to put in right place and properly clean the image properly.
Before:
(with border)
(without border)
After:
(with border)
(without border)
=> put the previewed image in right place and clean image(only w3mimgdisplay)

.gitignore, setup.py
The main reason for this is the presence of `develop` command in setuptools.
So by running `sudo python setup.py develop` - ranger gets installed, but you can easily make changes to the code and won't have to reinstall it.
You can read more about it here:
http://pythonhosted.org//setuptools/setuptools.html#development-mode
It basically links an egg, so I had to add an appropriate line to .gitignore as well.
=> Use setuptools if present

examples/vim_file_chooser.vim
Previously RangeChooser() would just fail silently in gvim. With this change, it will open an xterm and open ranger there. Everything else works as before.
=> Add ability to use ranger as file-chooser in gvim

ranger/data/scope.sh
* OSX does not support -E with /bin/echo
* On Linux the -E option is set by default
Fixes #344
=> Get rid of garbage `-E` character in preview display on mac

ranger/core/runner.py
os.environ['SHELL'] returns '/usr/bin/fish' which != 'fish'
this should fix fish compatibility for #300 and #341.
=> really fix #300 and #341

ranger/core/loader.py, ranger/ext/shutil_generatorized.py
a small patch to `CopyLoader` which would allow more flexible plugins (e.g. do mv/cp in elevated subprocess using some custom Loader for progress update)
=> make mv/cp generators yield progress

ranger/container/file.py, ranger/core/actions.py, ranger/data/scope.sh, ranger/gui/widgets/browsercolumn.py, ranger/gui/widgets/browserview.py
… instead of calling w3mimgdisplay for (potentially non-supported, e.g.
SVG files) images, which also has the side effect of making custom
previews for images impossible.
This patch also handles #263 using solution 3, in order not to break
backward compatibility:
> **Solution 3:** Add an another variable to indicate whether an image
> should be generated and ignore the image if it still is created. It would
> work like the previous solution but would not break the existing configs.
scope.sh has also been slightly refactored to take into account this
change.
Should also take care of #371.
---
````
One Scope to rule them all, One Scope to find them,
One Scope to bring them all and in the terminal preview them
In the Land of Ranger where the Data lies.
````
=> Use scope.sh for all the previews

ranger/api/commands.py, ranger/core/actions.py
I've fixed the handling of the methods of the `Actions` class in the `dump_commands` function. Previously their docstrings were completely ignored. The new behavior is described in the commit message of 45ee436 and is applied to all the commands, not only the `Actions` class methods.
Additionally I've added the documentation to some of these methods.
=> Fix the doc extraction for "dump_commands" and add some new documentation

ranger/ext/rifle.py
On Mac OS X the `$DISPLAY` environmental variable is never set. Checking for it to check if there is a graphical environment available will not work. I think it can be safely assumed that Mac OS X is always running with GUI.
Calling it "X" is a bit of a misnomer considering Mac OS X does not use X11, but I think it still conveys the meaning well. Or we could retcon the meaning of "X" on Macs to "Mac OS **X**". ;)
=> Fix the "X" rifle specifier for Mac OS X

ranger/data/scope.sh
Most (all?) `tr` implementations do not support unicode.
Use `awk` instead for turning extensions to lowercase.
=> scope.sh: Support unicode extensions

ranger/config/rifle.conf
It shouldn't be a security issue because the user still needs to enable the executable bit of the binary.
=> Allow the execution of the executable binary files via rifle

ranger/gui/curses_shortcuts.py
The filename on the second to last line of the screen is now properly
shortened.
=> Fix for issue #332. Broken file shortening.

ranger/gui/colorscheme.py
Some systems only provide *.pyc files
=> colorscheme: check for compiled python files

ranger/ext/rifle.py
Previously, rifle would recognize certain non-extensions as file extensions.  Three examples:
/etc/modules.d directory opening as a D source code file
./jpg directory opening as JPEG file
~/.mkv text file opening as an MKV movie file
These modifications only evaluate a file extension if it is part of a file and has a file name before a period.
=> Rifle's ext condition now handles fringe cases.

doc/ranger.pod, ranger/core/actions.py
Many shell utilities expect full paths.  The %s macro provides basenames in most usage cases, so I added %p/%P/%#p for explicitly retrieving full paths.
=> Added %p macro for full paths of selected files.

ranger/core/main.py
It seems like a good idea to document somewhere the fact that the previews are disabled for root. This patch appends an information to the <kbd>W</kbd> log.
=> core.main: Log the fact of disabling the file previews for root

ranger/ext/img_display.py
On OSX when using ranger inside tmux, images won't display if the setting is enabled. This is a workaround similar to Iterm2's [`imgcat`](https://github.com/gnachman/iTerm2/blob/7fb596f04b8e8c7e730efe1a033317f121a2f943/tests/imgcat)
=> update Iterm2 ImageDisplayer to work within tmux

ranger/core/fm.py
This adds [pqiv](https://github.com/phillipberndt/pqiv) support for ranger's `open_all_images` option.
It might also be nice to put pqiv somewhere in the default `rifle.conf`. I don't know how high priority it would have, but I'd say it's one of the more rarely installed image viewers.
=> open_all_images support for pqiv

ranger/container/fsobject.py, tests/ranger/container/test_fsobject.py
The old version relied on comparing integers to strings which is not
supported in Python 3 anymore and not a good practice in general anyway.
It was also the case that 'hello2' was ordered before 'hello' instead of
after, which I found to be non-intuitive.
=> Make natural_sort's behaviour better defined

ranger/core/actions.py
Sample usage:
:set_bookmark a /home/me/a
Motivation: make it easier to set bookmarks from environment variables
on rc.conf.
=> set_bookmark for directories other than the current

ranger/container/fsobject.py, ranger/core/linemode.py
Thanks to @Vifon for his help.  Fixes #520.  Conflicts with #521.
It might be worth considering making the `sizemtime` linemode the default, because it most closely resembles the output of `ls -l`.
=> Add MtimeLinemode and SizeMtimeLinemode

doc/ranger.1
A correction of a simple typo in one of the options described in the man page.
=> `draw_progress_bar_in_statusbar' does not exist

ranger/core/main.py
1. Use importlib instead of __import__ because the later messes up the global namespace within the plugin.
2. Try to load commands from the plugin, because it is a huge pain to inject new commands from within the plugin itself. I am aware of the commands file, but sharing a command by telling someone to paste some code at the end of a file isn't particularly fun.
=> 2 small changes to loading plugins

ranger/core/loader.py
In some fonts, character 'l' are indistinguishable from the numeral one. So better use 'L' instead.
=> Change ambiguous variable name 'l' to more meaningful 'line'

ranger/container/settings.py, ranger/ext/img_display.py
Fixed according to:
https://github.com/ranger/ranger/pull/600#issuecomment-228470987
> The first two would make sense in my opinion. Especially the one in settings.py as some dicts there already have trailing commas.
=> Add missing trailing commas

doc/ranger.pod, ranger/config/commands.py
The default `rc.conf` uses `scout` with the `-r` flag in several places, but the flag isn't documented.
=> Document -r flag for scout command

ranger/config/rc.conf
When I hit the `r` key, there was no white space after the prompt `open_with`...
It can be solved by simply adding one more `%` before `%space` to escape.
related to: #293
=> Fix map of open_with command

ranger/gui/widgets/view_miller.py
The incorrect part of the conditional checks whether a folder is currently focused but does not check if the setting `preview_directories` is `True`. This condition is already covered in the `self.columns[-1].has_preview()` function thus can be removed from the conditional.
=> Fix preview column displayed unintentionally

ranger/gui/widgets/statusbar.py
The full folder size was previously being shown when all files currently displayed were being shown, however in combination with filtering and hidden files this could make the size totally wrong.
=> Fix full folder size being shown incorrectly

ranger/gui/displayable.py, ranger/gui/ui.py
This results from finalize being called in order for the widgets. Previously when ranger changed viewmodes, it would delete then readd the widget object which meant that the finalize for the viewmode was called last instead of before console, which meant the finalize of the viewmode was setting
and overriding the cursor position.
Fixes #639.
=> Fix cursor being lost when changing viewmodes

ranger/data/scope.sh
Added a line to scope.sh for OpenDocument Text files (odt, ods, odp, sxw). I've used it for quiet some time and the preview seems to work. However I'm not sure about the exit code(s).
The preview is generated by [odt2txt](https://github.com/dstosberg/odt2txt). It is contained in the Arch Linux community repository as well as in the repositories of Ubuntu, Debian, Fedora, OpenSuse and probably more distributions.
Tell me what you think.
=> Added preview option for OpenDocument Text files using odt2txt

ranger/ext/shell_escape.py
This is required for shell commands to succeed with filenames that
start with the hash character. The 'mv' command invoked by 'bulkrename',
for instance, will fail with such files unless hashes are escaped.
=> add hash as an escaped character in shell commands

ranger/config/commands.py, ranger/core/runner.py, ranger/ext/get_executables.py
Now only the first token of TERMCMD needs to exist in PATH. Previously
the whole value was checked, which could contain additional parameters.
The check and term guessing were performed in two places. Now it's done
by the get_term() function to reduce the code duplication. In that
function the second check was indented one level deeper (relative to the
original code). Keeping both checks on the same level, while visually
pleasing, was conveying the wrong message. One never wants to perform
the second check if the first one fails. Nesting shouldn't be a problem:
if the nesting will need to be any deeper than this, this code will need
to be refactored anyway.
Fixes #613.
=> Refactor and improve the TERMCMD handling

ranger/core/linemode.py, ranger/ext/vcs/vcs.py
- replaced calls to subprocess.check_output by code downported from
Python 2.7
=> fix issue #695: FileInfo Linemode crashes Ranger on Python 2.6

ranger/config/rifle.conf, ranger/data/scope.sh
When 7zip archives created with -mhe=on (also known as "encrypt file list") are selected by ranger, the application crashes, because als (or rather 7z) promps for a password to list the files in the preview.
To prevent this, the 7z command can use the -p option with an empty string, preventing the preview for 7z archives with encrypted file lists.
The same applies when such archives are opened, causing an error about a wrong password instead. Archives without the -mhe=on option are not affected by this.
Alternatively "als -O-p" can be used to pass the option to 7z instead of using it directly.
=> fixed 7z crash

ranger/core/fm.py
Previously the displayer was not changed after the initialization, so only the value read from rc.conf was used.
=> Update the image preview method upon setting it in runtime

ranger/ext/img_display.py
I've fixed the 'i' maximization of the preview pane. Previously it didn't affect the preview size.
=> urxvt previews: Allow the preview maximization

examples/bash_automatic_cd.sh
Spent a while trying to figure out why the example script in `bash_automatic_cd.sh` didn't work on my Mac (OS X 10.11.6). Running `which ranger` on my machine produces `/usr/local/bin/ranger`, not `/usr/bin/ranger` (which I'm guessing applies to linux). Versions I'm using:
- ranger-stable 1.7.2
- Python 2.7.10
=> Add correct path to ranger on OS X

ranger/__init__.py, ranger/api/commands.py, ranger/core/actions.py, ranger/core/fm.py, ranger/core/main.py, ranger/ext/logutils.py, ranger/ext/vcs/vcs.py
You can read about the reason behind this PR on this issue:
https://github.com/ranger/ranger/issues/713
Four different ways of outputting stuff were used:
- printing out on stdout:
can be used only when the curses interface is not running,
is usually used on critical error before exit ranger.
- printing out on stderr:
can be used only when the curses interface is not running,
is usually used for warnings.
- appending string to a queue in the FM class
(these are the logs shown by the curses log viewer)
- background processes and task usually use the `FM.notify` function
to show a message on the bottom bar of ranger. Moreover this fuction,
if the debug mode is active, will print the stack trace and exit the program.
First of all it is difficult for new dev to understand which method of …
=> Migration to standard logging library

ranger/core/actions.py
Fixed the trailing space in config bug.
Basically, trailing spaces were not stripped, and if one unknowingly leaves a trailing space in config file, the line is ignored. Fixed by adding space to rstrip in actons.py.
=> Fixed trailing space bug in config parsing.

ranger/gui/widgets/view_multipane.py
By changing it, this means the columns will use the entire width if the geometry allows for it.
Instead of using a hard offset of one for the width of the column, this just changes the next position of the column to be one further than the column width.
=> Change how column widths are calculated

ranger/core/main.py, ranger/ext/vcs/vcs.py, ranger/gui/ui.py
The exit routine code is executed on every program run, thus
I consider it pretty important.
I found out that this part of the code was very confuse and complex,
thus very difficult to modify.
Moreover the message and the exit code brought up with the
`sys.exit` function or the `SystemExit` exception were completely ignored.
In fact the `return` statement into the exception handler was bypassed by
the `finally` block.
I made a little bit of refracotring and I hope that this will make easier to
mantain this part of the code.
The second commit is a simple pep8 error fix
=> Cleaned up exit routine code

ranger/config/commands.py, ranger/gui/quick_jump.py
Vifon reported some issues two wees ago, and while I studied the cause, I found that the problems are caused by "reimplement" stuff in the quick_jump class instead of scout.execute. I think this pull request is a better integration of the quick-jump mode into scout.
=> restructed quick-jump/scout execution

doc/rifle.1, doc/rifle.pod, ranger/ext/rifle.py
This change adds a command line option to the `rifle` standalone script to allow specifying a custom configuration file instead of the default.
- new `-c CONFIG_FILE` option added to `rifle.py` arg parsing
- move `conf_path` logic to after arg parsing to allow the `-c` option to affect the process (if `-c` is set, that file will be used with no questions asked and without attempting to fallback to another default config file)
- rifle man page updated to suite.
I use rifle all the time, both with ranger and from the shell as an `xdg-open` replacement. However I find there are generally 2 contexts I want to use it in - from the shell where preference is for opening in text applications (eg. vim, atool for viewing archives), and the other is from gui …
=> Custom config file option for rifle

doc/ranger.1, doc/ranger.pod, doc/rifle.1, ranger/config/commands.py, ranger/config/rc.conf
This PR modifies the behaviour of the quit commands to avoid accidently quitting ranger if tasks are running.
- `quit` and `quitall` will not exit ranger if tasks are running
- `quit!` will force-quit ranger (ie. quit even if tasks are running)
- useful when long tasks are running in the background and the user has the potential to forget about them, for example extracting archives or copying large files.
- similar feature requested in #739
=> don't quit if tasks are running

ranger/config/commands.py
cd tab completion didn't work in the presence of real path argument '-r'.
Fixed that.
- Bug fix
- Operating system and version: Linux 4.4.45
- Terminal emulator and version: gnome-terminal 3.22.1
- Python version: 2.7.13 and 3.6.0
- Ranger version/commit: ranger-master 1.9.0b5
When '-r' argument is present, user given path must be self.arg(2) not self.arg(1).
That was the reason why tab completion didn't work with '-r'.
The bug was a small glitch. Not much to say.
Tested manually input some directories and press tab by hand.
=> config.commands.cd.tab: Now tab works fine with '-r'

ranger/config/commands.py, ranger/core/actions.py
- Bug fix
Some commands crash with unhelpful error messages. For example with flat - calling `:flat` currently results in:
```
'<' not supported between instances of 'NoneType' and 'int'
```
This PR improves the error messages shown when calling the following commands with no arguments:
- flat
- chain
- map (including cmap, tmap, pmap)
- change_mode
=> Improve error messages when calling commands without args

doc/ranger.1, doc/ranger.pod, ranger/config/commands.py, ranger/config/rc.conf, ranger/container/settings.py
Now you can use case-insensitive completion in cd command.
`cd Me<tab press>` becomes `cd MEGA`
`cd do<tab press>` becomes `cd Downloads` with double tab becomes `cd downloads`
`cd r<tab press>` becomes `cd ReWrite`
- Operating system and version: Linux 4.9.11-1-ARCH
- Terminal emulator and version: xterm(327)
- Python version: 2.7.13 and 3.6.0
- Ranger version/commit: 1.9.0b5
To simplify completion.
I only ran `make test` and used it about two days.
=> Add cd case-insensitive completion

doc/ranger.1, doc/ranger.pod, doc/rifle.1, ranger/config/commands.py, ranger/config/rc.conf, ranger/container/settings.py
Finds matching directories recursively with given path string when a user presses tab key.
For example, ":cd /u/l/p<tab press>" => ":cd /usr/lib/python".
- Operating system and version: Linux 4.4.45
- Terminal emulator and version: gnome-terminal 3.22.1
- Python version: 2.7 and 3.6
- Ranger version/commit: 1.9.0b5
To make easier to navigate directories with cd command
Ran "make test"
=> config.commands.cd: Add cd tab completion with less typing functionality

ranger/config/rifle.conf
Add nomacs image viewer to the default list of image viewers.
- Operating system and version: Arch Linux with testing repositories
- Terminal emulator and version: rxvt-unicode 9.22
- Python version: 3.6.1
- Ranger version/commit: 1.8.1
Adds [nomacs](https://nomacs.org/) to the default list of supported image viewers to open files with.
I was previously a user of mirage, but development has ceased on that. [nomacs](https://nomacs.org/) seems like a solid replacement as it's light weight, been around for a while, and still in development. It is also [available in the default repositories](https://nomacs.org/download/) of a number of distributions.
This change eliminates the need for me to have a custom rifle.conf. 
Tested by …
=> Add nomacs image viewer support

ranger/core/main.py
- Bug fix
- Operating system and version: Mac OS X El Captain
- Terminal emulator and version: iTerm2
- Python version: Python 2.7.13
- Ranger version/commit: ranger-master 1.9.0b5
Simply move the rc.conf loading chunk after plugin so that default_linemode plugin can be load propoerly
To make the default_linemode plugins other plugins, that rc.conf might relies on, work properly.
If you run without --debug it roughly work but pop this annoying message in terminal:
```.bash
Invalid linemode: devicons; should be metatitle/sizemtime/filename/mtime/fileinfo/permissions
```
[Issue #3](https://github.com/alexanderjeurissen/ranger_devicons/issues/3)
If run with --debug, you get error message:
```.bash
ranger version: ranger-master 1.9.0b5
Python version: 2.7.13 (default, Dec …
```
=> Switch the order of experimental plugin loading and rc.conf sourcing

ranger/config/commands.py, ranger/config/rc.conf
Implement a yank command instead of the long mappings for yn, yd, yp and ys.
The command can use any of pbcopy, xclip or xsel, depending on what's available.
Behaviour for yn, yd and yp has changed. Instead of the highlighted file they operate on the selection, defaulting to the highlighted file if nothing's selected.
The yank command makes it easier to use multiple clipboard managers, xclip instead of xsel for example. It also groups the behaviour of several long mappings.
Manually tested the command in all it's incantations.
=> Yank command

ranger/config/commands.py, ranger/container/directory.py, ranger/container/settings.py, ranger/core/main.py
Added global_inode_filter_type setting for global filtering of file types. Uses same logic as the filter_inode_type command.
Sets the `global_inode_filter_type` to `'d'` (for directory) when --choosedir flag is used
Addresses request for global filtering of files when using --choosedir= in issue #821 
Have done basic testing by hand to ensure functionality
=> Show only directories when using --choosedir

ranger/core/main.py
- Bug fix
Separated global_inode_type_filter from --choosedir
Added --show-only-dirs flag
See #888
=> moved inode filtering from choosedir to show-only-dirs

ranger/config/rifle.conf
Adds support for opening `epub` ebook files with ebook-viewer (included with Calibre).
- Operating system and version: Arch Linux w/ testing repos
- Terminal emulator and version: rxvt-unicode 9.22
- Python version: 3.6.1
- Ranger version/commit: ranger-stable 1.8.1
Adds a sane default for opening epub files. Calibre is a commonly used ebook management solution that includes an epub reader: ebook-viewer.
epub is a common ebook format. This adds support built-in support for opening such files from ranger.
Manually - rifle.conf addition only.
=> Open epub files with ebook-viewer

ranger/ext/direction.py
Moving half a page down and back up should put the user in the original position. It was true only if the file count was even. If it was odd, the user ended up one file above the originally focused one.
=> Make the pagewise scrolling symmetrical

ranger/core/main.py
Ignore the RANGER_LOAD_DEFAULT_RC environmental variable if the user config doesn't exist or is unreadable because not loading any config would result in an unusable ranger instance.
=> If the user config is not available, always load the global one

.flake8, .pylintrc, ranger/container/directory.py
- Terminal emulator and version: urxvt 9.22 and tmux 2.3
- Python version: 3.6.2
- Ranger version/commit: a81b6ecf750aba0eb9efceea88f43ffbf3729700
Reenable linting for indentation.
Will make it much easier to parse and understand the codebase in the future. Not hard to make new code compliant.
`make test`
=> tests: Reenable indentation linting

ranger/config/rifle.conf
- Operating system and version: macOS Sierra
- Terminal emulator and version: iTerm2 3.1.5
- Python version: Python 3.6.2
- Ranger version/commit: 1.9.0b5
- Locale: ??? What is it?
- [x ] The `CONTRIBUTING` document has been read **[REQUIRED]**
- [ x] All changes follow the code style **[REQUIRED]**
- [ x] Changes require config files to be updated
- [x ] Config files have been updated
You can open PDFs with Preview in macOS with just an enter.
Eases your life.
Easily open PDFs in Mac
Test wouldn't be necessary for this minor change. I tried to run tests but ran into:
```
AttributeError: 'TreeRebuilder3k' object has no attribute 'visit_joinedstr'
```
Nothing
=> Open PDFs with Preview in macOS

ranger/data/scope.sh
It may cause a small overhead of checking the EXIF data for each file. Possible alternatives:
- Running `convert -auto-orient` for each and every image without doing this check. The preview will get cached but then each and every image will get copied to the cache directory usually with no such need.
- Commenting out this code by default, so it's easily available but still opt-in.
Fixes #927.
=> Rotate the image previews according to the EXIF data

ranger/data/scope.sh
By default they are rendered for the FullHD resolution as it should be both legible on any resolution and generate not too large files.
The order of handing the previews was changed to handle the image-based previews first as they are easy to toggle anyway and it makes sense for them to override any other preview type if enabled and available.
=> scope.sh: Add the image-based PDF previews (disabled by default)

ranger/ext/vcs/vcs.py
Use "chg", a faster client to mercurial shipped with mercurial itself. This fixes the unrecoverable hang I get when entering a folder with many hg repos.
- Bug fix
- Terminal emulator and version: Gnome terminal
- Python version: 3.6
- Ranger version/commit:  5bd92b3
- Locale: en_US
Call chg instead than hg for much better performance
Necessary if we want to use vcs_enabled_hg inside folders containing many hg repos.
Only empirical testing.
=> Faster mercurial vcs

ranger/container/file.py
- Bug fix
Fixes bug introduce with change of linemode variable to lazy_property
- Locale: 
Fixes regression introduce by commit  433a44f9bdbd8d01254559815b5dc349d44e46f8
"default_linemode" is applied only to directories. Files are omitted due to
linemode override in 'File' class by 'filename' linemode.
=> Fix bug with default linemode not applied for files

ranger/ext/img_display.py
Additional path to check for W3MIMGDISPLAY_PATHS, to fix w3m image previewing on OpenBSD.
- Bug fix
- Operating system and version: OpenBSD 6.1 amd64
- Terminal emulator and version: rxvt-unicode 9.22
- Python version: 3.6.0/2.7.13
- Ranger version/commit: 1.7.2
Added the correct path to check for w3imgdisplay on OpenBSD systems
Image previewing does not currently work on OpenBSD (though it has since been fixed in the OpenBSD port).  I'd like to get this change in upstream so there are fewer patches for the port.
All tests.  Shouldn't affect anything else in the codebase.
=> Added the w3mimgdisplay path for OpenBSD systems to W3MIMGDISPLAY_PATHS

ranger/core/fm.py, ranger/ext/img_display.py
Adds support for image previews for terminology (https://www.enlightenment.org/about-terminology)
Adds `TerminologyImageDisplayer` class
Works well (Terminology Version: 1.0.99).
Even for animated gifs ! It could probably work with videos too.
I couldn't make it work with TMUX.
=> Implement the terminology-based image previews

doc/ranger.1, doc/ranger.pod, doc/rifle.1, ranger/config/rc.conf, ranger/container/settings.py, ranger/ext/img_display.py
Add two config options "iterm2_font_width" and "iterm2_font_height" that
override the default values of _minimum_font_width and
_minimum_font_height in ITerm2ImageDisplayer.  The default values may
cause preview distortion if set too high (Issue #499) or result in the
preview being smaller than necessary if set too low.
- Bug fix
- Operating system and version: OSX
- Terminal emulator and version: iTerm2 3.1.3
- Python version: 2.7.10
- Ranger version/commit: ranger-master 1.9.0b5
Add config options: "iterm2_font_width" and "iterm2_font_height" to replace the hardcoded default font dimensions in ITerm2ImageDisplayer:
```
_minimum_font_width = 8
_minimum_font_height = 11
```
Issue #499 
A default font width that's too high can cause …
=> Add config options for iTerm2 font size (related to issue #499)

ranger/config/commands.py
The tab completion for `:set column_ratios <TAB>` previously used the literal list representation of this setting (e.g. `[1, 3, 4]`) which cannot be used in this syntax. Now this list is joined into a single comma-separated string that is actually usable (e.g. `1,3,4`).
=> Fix column_ratios tab completion

ranger/ext/rifle.py
There's 4 possible situation:
1. `VISUAL` set, `EDITOR` set
2. `VISUAL` set, `EDITOR` not set
3. `VISUAL` not set, `EDITOR` set
4. `VISUAL` not set, `EDITOR` not set
All but _No.2_ are already properly handled.
Behavior can differ depending on whether you have an old or a new `rifle.conf` in cases
_No.1_ (if the variables differ the new approach prefers `VISUAL` instead of `EDITOR`)
and _No.2_ (new approach will use `VISUAL` whereas the old approach would've fallen back to _vim_).
_No.3_ is likely the most common case and works almost identically with either approach.
_No.4_ still falls back to _vim_ as before.
Fix #1048
=> Make new `rifle` behavior backwards compatible.

ranger/config/rc.conf
For consistency with vim `gt` still means _go to the next tab_ the map
for _go to /tmp_ is now `gp` (first available letter in `/tmp`).
Fix #1040
The map for `/tmp` was useless, now it's not.
The map for `/run/media/$USER` was missing and fit in well with both `/media` and `/mnt`.
Maybe the map for `/media` should also include `$USER`?
Possibly we should handle the case where `$USER` is `root` specially, dropping the `$USER` part.
Since these "hardcoded" maps are getting somewhat cluttered, maybe we should consider having a new bookmarks namespace with system directories.
Tested both maps.
=> Solve map conflict for `gt`.

ranger/core/main.py
The metavar "PATH" is likely being confused with the environment
variable PATH. OUTFILE makes it clearer that the "PATH" in question is a
file.
- Operating system and version: Arch Linux, Kernel 4.14.15-1-ARCH
- Terminal emulator and version: termite v13
- Python version: 3.6.4
- Ranger version/commit: 1.9.0
- Locale: en_GB.UTF-8
The PATH metavar has been changed in the help text (`ranger --help`) to avoid confusion with the environmental variable of the same name.
Avoid confusion (see above)
`make test` has been run. All tests passed.
=> change PATH to OUTFILE to avoid confusion

ranger/config/rifle.conf
Add geeqie image viewer to the default list of image viewers.
- Operating system and version: Arch Linux with testing repositories
- Terminal emulator and version: termite 13-1
- Python version: 3.6.4
- Ranger version/commit: 1.9.0
Adds [geeqie](https://github.com/BestImageViewer/geeqie) to the default list of supported image viewers to open files with.
Geeqie is a lightweight, well-maintained image viewer. Having this included in the default rifle.sh eliminates the need for me to use a custom config.
Tested that geeqie opens images.
=> Add geeqie image viewer support

ranger/data/scope.sh
Bash v3 doesn't support the `,,` syntax for lowercasing. This is
relevant on Mac OS which still comes with bash v3.2.
Using `:upper:` and `:lower:` with `tr` takes into account the locale so
this allows letters with diacritical marks in extensions.
This behavior may not be desirable.
Fixes #1072
- Bug fix
=> Make scope.sh backwards compatible with bash v3

ranger/gui/curses_shortcuts.py
Python changed an error from `TypeError` to `ValueError` in version 3.5
now we catch both for backwards compatibility.
Relevant issue: https://bugs.python.org/issue22215
Fixes #990
Fixes #1045
Fixes #1079
Fixes #1082
Fixes #1086
=> Catch the right errors in addstr

doc/ranger.1, doc/ranger.pod, ranger/config/rc.conf, ranger/container/settings.py, ranger/gui/widgets/view_base.py
Replace the "..." hints with the full contents of the subkeymaps. Might get troublesome with the bigger keymaps like the chmod one (<kbd>+</kbd> and <kbd>-</kbd>) but the "..." hints are just as uninformative in this case in my opinion.
The hints are grouped by the first key before sorting these groups, so the submaps should be easy to read.
=> Show the full keybindings in the key hints

ranger/config/rifle.conf
Fixes #1128
Changed from `flat` to `flag` for final pdf match:
https://github.com/ranger/ranger/blob/f3d8c57b1fa24f0fa8b4c3d2e5f96bf6a2f9778e/ranger/config/rifle.conf#L154
- Bug fix
ranger version: ranger-master 1.9.1
Python version: 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
Locale: None.None
Changed from `flat` to `flag` for final pdf match:
https://github.com/ranger/ranger/blob/f3d8c57b1fa24f0fa8b4c3d2e5f96bf6a2f9778e/ranger/config/rifle.conf#L154
It breaks the use of `open` with PDFs if using the default rifle config.
If none of the listed PDF applications are installed (e.g. OS X), then PDFs won't open with the associated program and `open`.
#1128 
`make test`
They don't.
=> Fix typo for pdf in rifle.conf

ranger/ext/rifle.py
- Breaking changes
Some MIME types are not found by rifle. With an additional test with the mimetype command after the file command returns 'application/octet-stream' rifle should now be able to recognize all known mime types in the system.
=> ext.rifle: Additional Check for mime type with mimetype command

doc/ranger.1, doc/ranger.pod, ranger/config/__init__.py, ranger/config/commands.py, ranger/config/rc.conf, ranger/core/main.py
Both rc.conf and commands.py are now additionally loaded from
`/etc/ranger` if they exist.
Fix #869
Not sure where we document config file locations.
Issue #869 asks for system-wide configuration files. People usually expect this behaviour.
I've tested under python2.7, further tests under all versions since 2.6 should be performed.
=> Load system-wide configuration files.

examples/rc_emacs.conf, ranger/config/rc.conf, ranger/gui/ui.py
Changing the tmux window title to "ranger" was not guarded for the
presence of the tmux executable, this tripped up at least one user with
an `rc.conf` that still `set update_tmux_title true`.
While the behavior is *not-a-bug*, I expect most people'd rather have
the setting enabled by default since "python" is a less useful window
title.
Fix #1042
Tested with and without tmux "installed" inside and outside of a tmux session.
=> Guard tmux title changes

ranger/config/rc.conf
Because of `udisks2` `/run/media/$USER` is becoming a common directory
for automounting, this adds a keybinding to go there (using the first
available letter in the path).
Similarly the binding for `/media` now points to `/media/$USER`, because
for example ubuntu adopted this new location.
I believe the `$USER` parts have to do with security, giving only the
user that mounted a filesystem access to it.
These locations are already common but as I understand it not definite yet. We could wait until the new FHS spec is finalized.
=> Update bindings for media directories

ranger/ext/human_readable.py
ranger will fail if `automatically_count_files false` is set.
- Bug fix
```
ranger version: ranger-master 1.9.0
Python version: 3.6.4 (default, Jan  5 2018, 02:35:40) [GCC 7.2.1 20171224]
Locale: en_US.UTF-8
Current file: '/home/laktak'
Traceback (most recent call last):
File "/home/laktak/ranger/ranger/core/main.py", line 196, in main
fm.loop()
File "/home/laktak/ranger/ranger/core/fm.py", line 390, in loop
ui.redraw()
File "/home/laktak/ranger/ranger/gui/ui.py", line 338, in redraw
self.draw()
File "/home/laktak/ranger/ranger/gui/ui.py", line 365, in draw
DisplayableContainer.draw(self)
File "/home/laktak/ranger/ranger/gui/displayable.py", line 256, in draw
displayable.draw()
File "/home/laktak/ranger/ranger/gui/widgets/view_miller.py", line 100, in draw
DisplayableContainer.draw(self) …
```
=> fix automatically_count_files false

.gitignore, ranger/core/main.py, tests/ranger/core/test_main.py
Fix for #1052 
- Bug fix
- Operating system and version: Mac OS High Sierra 10.13.3
- Terminal emulator and version: iTerm2 3.1.5
- Python version: 3.6.1
- Ranger version/commit:  324e5af
- Locale: LANG="ru_RU.UTF-8"
if cwd is unresolved, home directory will be used instead
https://github.com/ranger/ranger/issues/1052
manual tests + unit testing
=> Deleted parent handled incorrectly

doc/ranger.1, doc/ranger.pod, examples/rc_emacs.conf, ranger/config/rc.conf, ranger/container/settings.py, ranger/gui/widgets/statusbar.py
Fixes #1087
Useful on high-latency filesystems as it avoid calls to statvfs system
call which costs: (number of redraw) * latency.
- Operating system and version: linux
- Python version: 3.6
- Ranger version/commit: c2b9dd31
- Locale: UTF-8
This patch adds a new option to hide the freespace from the status bar.
see issue #1087
=> Add new option to disable display of free disk space in statusbar

ranger/core/main.py
- Bug fix
- Operating system and version: Archlinux 4.15.15-1-ARCH
- Terminal emulator and version: termite 13-2
- Python version: 3.6.4
- Ranger version/commit: 1.9.1
- Locale: en-US
Ranger crashes when launching with --cmd "flat 1" command.
This commit set the directory before running the command arguments
There was a bug report about it.
#1137 
I tested some other commands and it seems to be working fine. (--cmd "terminal", --cmd "grep")
I'm not the most knowledgeable about this project, could you confirm others areas of the codebase are not affected by this? Thanks
=> Enter directory before executing command arguments Issue #1137

ranger/core/actions.py, ranger/core/fm.py
Remove the check preventing the active tab from being saved.
Fixes #883
The limit on the number of tabs is removed because it's weird that you can get more tabs except using the most obvious way `tab_new`.
The code only implicitly assumed tab indices have to be numbers in one spot so I patched that, tabs are now ordered lexically unless they're both numbers, this resembles ranger's natural ordering.
=> Save all the tabs, including the active tab.

ranger/config/commands.py
This is analogous to 6cae0ed but with files, not directories.
Same as #181, but for files. I use `f` quite often, and it's common to open a file only to find that a command has been unintendedly executed. Let's add a delay. It shouldn't really affect anyone.
=> Add delay after opening (quickly_executed) a file

ranger/config/commands.py, ranger/config/rc.conf, ranger/container/fsobject.py
fixed yank file name without extension with multiple files selected.
and changed map `yw` to `y.` ref. pr #1174
fixed yank file name without extension with multiple files selected.
- Bug fix
- Locale: 
fixed yank file name without extension with multiple files selected.
fixed yank file name without extension with multiple files selected.
and changed map `yw` to `y.` PR #1174
Tested with multiple files selected, all working
=> Fixed yank name without extension in multiple files

setup.py
`colorschemes.txt` markup was improved and the file got a `.md`
extension to match.
Fixes #1221
=> Update colorscheme docs path in setup.py

doc/colorschemes.md
Added basic instructions on how to add a context key with a working
example. This includes adding it to the `CONTEXT_KEYS` constant and
letting ranger know what it means.
Added a more comprehensive `Context` section in the colorschemes.md doc
It makes it easier to learn how to create a more dynamic colorscheme
=> Revamped context section of the colorscheme doc

ranger/ext/rifle.py
`su` on macOS requires the user to be explicitly specified for a command
to be run.
- Bug fix
- Operating system and version: macOS High Sierra 10.13.6
- Terminal emulator and version: Kitty 0.11.3
- Python version: 2.7.15 (default, Jul 15 2018, 16:11:37) [GCC 4.2.1 Compatible Clang 5.0.2 (tags/RELEASE_502/final)]
- Ranger version/commit: ranger-master 1.9.1 53e48ed0
=> Fix run as root on macOS

ranger/gui/widgets/pager.py
- Bug fix
- Terminal emulator and version: rxvt-unicode v9.22
- Python version: 3.7.0
- Ranger version/commit: 1.9.1
- Locale: US
A bare `return` in generators raises `StopIteration` (this is backwards
compatible). Using `StopIteration` raised a warning in 3.6.x and raises an
Error in 3.7.0 (and probably upwards). So this is a compatibility patch that shouldn't be too controversial (even the `try/except` blocks on `StopIteration` should still work, since the same error is raised.
See https://docs.python.org/3/reference/simple_stmts.html#grammar-token-return_stmt
Ranger crashes on Python 3.7.0 currently.
The crashes.
All (the pylint ones obviously give a lot of warnings).
They don't, as the bare return statement still raises a `StopIteration`. I …
=> Replace StopIteration with bare return

examples/bash_automatic_cd.sh
Hard coding the path of ranger prohibits the `bash_automatic_cd.sh` script
from working when the user has installed ranger in a different path such
as in `/usr/local/bin/`, or `~/.local/bin/` etc.
=> Remove hard code of ranger path

ranger/core/actions.py
Was erroneously checking the entire selection for being *a* directory
but a list of 1 or more files/directories is obviously not a directory.
Fixes #1269
=> Check whether tfile is a dir not the entire selection

ranger/config/rc.conf
- Operating system and version: Arch Linux x86_64
- Terminal emulator and version: terminator 1.91
- Python version: 3.7.0 (default, Jul 15 2018, 10:44:58) [GCC 8.1.1 20180531]
- Ranger version/commit: ranger-master 1.9.1
- Locale: En/GB
Add <C-g> as an alias to <ESC> in console
Mimics the behaviour of `C-g` in Emacs.
I couldn't find a line in the manual where I could document this change, so I guess this will have to wait.
=> Add `C-g` as an alias to `ESC` in console

ranger/gui/ui.py
- Bug fix
ranger version: ranger-master 1.9.1
Python version: 3.7.0 (default, Jul 15 2018, 10:44:58) [GCC 8.1.1 20180531]
Locale: ja_JP.UTF-8
Not all test pass, but it ain't my fault.  This shit's a joke, yo:
```■ LC_ALL=C make test
Running pylint...
pylint ./ranger/container ./ranger/core ./ranger/api ./ranger/ext ./ranger/gui ./ranger/colorschemes ./ranger/__init__.py ./doc/tools/convert_papermode_to_metadata.py ./doc/tools/print_colors.py ./doc/tools/print_keys.py ./doc/tools/performance_test.py ./examples/plugin_new_sorting_method.py ./examples/plugin_hello_world.py ./examples/plugin_chmod_keybindings.py ./examples/plugin_avfs.py ./examples/plugin_file_filter.py ./examples/plugin_pmount.py ./examples/plugin_fasd_add.py ./examples/plugin_ipc.py ./examples/plugin_new_macro.py …
```
=> Applies Tilde Setting to Window Title

doc/ranger.1, doc/ranger.pod, ranger/config/rc.conf
- Operating system and version: Arch Linux x86_64
- Terminal emulator and version: terminator 1.91
- Python version: 3.7.0 (default, Jul 15 2018, 10:44:58) [GCC 8.1.1 20180531]
- Ranger version/commit: ranger-master 1.9.1
- Locale: En/GB
Add mapping to open console and pre-fill it with previous command.
Behaviour assigned to Ctrl-p.
Follows from the discussion in #1293.
Non-essential change which can be removed if we find a better use for `Ctrl-p`.
=>  Add mapping to open console and pre-fill it with previous command

ranger/core/actions.py
The `%any` macro is very useful for commands that know about bookmarks.
Bookmarks are just short names for paths really, so it'd be nice if they
could be used with any commands that take paths as arguments.
Now they can! `%any_pathX` where `X` refers to the which `<any>` the
macro corresponds to (`%any_path` is synonymous with `%any_path0`) is
replaced with the path of the bookmark entered if that bookmark exists.
Fixes #1277
=> Add the %any_path macro

ranger/core/actions.py
If `selection == False` don't operate on the entire selection (the marked files) but only on the file under the cursor.
Inconsistent, I noticed `move to=100 percentage=true` works as expected
but `move right=1 selection=false` doesn't. You need to pass `False`,
most other values test as `True` in python, so `true` works *but*
surprisingly imo, `false == True`.
Fixes #1233
=> Add selection argument to move action

ranger/config/rc.conf, ranger/core/actions.py
to shift tabs, use new shortcuts ALT-p and ALT-o
- Operating system and version: Ubuntu 16
- Terminal emulator and version: GNOME Terminal 3.18.3
- Python version: Python version: 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
- Ranger version/commit: ranger-master 1.9.1 / f855979587bd918f0d32c0caba79ab4b4aa531cf
- [] All new and existing tests pass **[REQUIRED]**
Shift the selected tab left or right.
Uses shortcuts added to rc.conf: ALT-p to shift tab right, ALT-o to shift tab left.
Let's you organize the tabs so you can place them in the order you want.
Tested ok with different numbers of tabs open  (1 tab, 2 tabs  ... 9 tabs).
Tested ok with close tab/restore tab.
Tested ok with save_tabs_on_exit.
None.
Running the …
=> Added: shift tabs right/left

ranger/colorschemes/default.py, ranger/colorschemes/snow.py, ranger/gui/color.py
Stop lying and use bright instead of bold. Fall back to dim white instead of bright black in terminals that don't support bright colors.
=> Boldisnotbright

ranger/ext/img_display.py
Moved the format conversion line from the stream section to the general
one, as PIL does not autoconvert on save
- Bug fix
the diff speaks for itself in this case
#1312 Example of the bug in the wild
tested on a CYMK jpg image from wikipedia. It might be worthwhile to wait until I test on some different formats (palette gifs?). I have a bus to catch though for now :sweat_smile:. But it should work fine.
=> Fix for issue #1312 (wrong color format)

ranger/gui/widgets/browsercolumn.py, ranger/gui/widgets/pager.py
- Operating system and version: 4.18.11-arch1-1-ARCH
- Terminal emulator and version: rxvt-unicode (urxvt) v9.22 
- Ranger version: ranger-master v1.9.2-9-g41e19fd3
- Python version: 3.7.0 (default, Sep 15 2018, 19:13:07) [GCC 8.2.1 20180831]
Enabled the ability to use mouse wheel to scroll through files without going into preview.
It resets to the begin whenever the selected file changes.
This addresses feature-request (Issue) #147 
I've run the default test. With the exception of introducing a new variable to the pager, there doesn't seem to be major changes
=> initial mouse wheel scroll support in preview (Issue #147)

ranger/ext/rifle.py
The code that used it was removed by [this](https://github.com/ranger/ranger/commit/1687e0f41f172cef6923f75f4c6f1038f19671dc#diff-69c755cc0a116b02658af55ef9885afb) commit.
=> Delete unused variable

ranger/core/actions.py, ranger/gui/widgets/browsercolumn.py, ranger/gui/widgets/pager.py
- Bug fix
- Operating system and version:  Archlinux x86_64
- Terminal emulator and version:  rxvt-unicode (urxvt) v9.22
- Python version:  3.7.0 (default, Sep 15 2018, 19:13:07) [GCC 8.2.1 20180831]
- Ranger version/commit:  ranger-master v1.9.2-39-g4d84abad
- Locale:  en_US.UTF-8
Scrolling in a pager (:display_file) was restored and at the same time new ability to scroll preview column is saved.
Fixes #1347
=> Restoration of scrolling in pager.

ranger/container/bookmarks.py, tests/ranger/container/test_bookmarks.py
If it is, the os.rename is performed on the original file path instead of overwriting the symlink.
- Operating system and version: Linux workstation 4.19.8-arch1-1-ARCH #1 SMP PREEMPT Sat Dec 8 13:49:11 UTC 2018 x86_64 GNU/Linux
- Terminal emulator and version: rxvt-unicode (urxvt) v9.22 - released: 2016-01-23
- Python version: Python version: 3.7.1 (default, Oct 22 2018, 10:41:28) [GCC 8.2.1 20180831]
- Ranger version/commit: ranger 1.9.2
- Locale: en_GB.UTF-8
When the bookmarks file is a symlink, it is overwritten on every save with a new file.
This pull requests implements a check to see if this is true, and performs the save at the link original location.
If the file is a plain file, the original behaviour remains.
I like having the bookmarks …
=> Added check if bookmark file is a symlink.

ranger/data/scope.sh
provides the ability to preview DJVU files with text preview, just like PDF files
Requires `djvutxt` program provided by `djvulibre` to convert
Very simple implementation on `scope.sh` that provides the ability to preview DJVU files with text preview, just like PDF files, only requires `djvutxt` to be installed on system
These changes help with previewing DJVU files with text conversion, so that they can be previewed just like PDF documents. This solves the problem of not having a text preview of DJVU files
No tests have been run, as this doesn't affect any of the existing code base.
=> added support for DJVU text conversion

ranger/core/main.py
Adds support for loading plugins located in `<ranger.args.datadir>/plugins/` (defaults to `~/.local/share/ranger/plugins/`). Plugins need to have a `__init__.py` file as an entrypoint.
Solves issues with plugin standardization, installation, uninstallation, and updating. It is intended that plugins will be `git clone`d into the new plugin location and managed there. Also makes it much easier to create a ranger-plugin-manager. Plugins will have to be updated to work with the new location.
=> Load plugin directories located in ~/.config/ranger/plugins

ranger/gui/curses_shortcuts.py
When in input mode (e.g. search, :mkdir, :rename, etc.), pressing Ctrl+Space makes ranger crash
This will fix this issue
Crash example:
```
ranger version: ranger-master 1.9.2
Python version: 3.7.2 (default, Jan 10 2019, 23:51:51) [GCC 8.2.1 20181127]
Locale: el_GR.UTF-8
Current file: '/home/spiros/1. "aaa" \'aaa\''
Traceback (most recent call last):
File "/usr/lib/python3.7/site-packages/ranger/gui/curses_shortcuts.py", line 36, in addstr
self.win.addstr(*args)
ValueError: embedded null character
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/lib/python3.7/site-packages/ranger/core/main.py", line 195, in main
fm.loop()
File "/usr/lib/python3.7/site-packages/ranger/core/fm.py", line 394, in loop
ui.redraw()
File …
```
=> fix Ctrl+Space crash

ranger/data/scope.sh
This pull request adds commented-out code for DjVu and ePub image previews to `scope.sh`. It also includes some trivial robustness improvements that don't merit a separate pull request.
- Operating system and version: Debian GNU/Linux 10
- Terminal emulator and version: xterm 340
- Python version: 3.6.8rc1
- Locale: en_GB.UTF-8
--> There are some failures in `make test_doctest`, but they're unrelated to this pull request.
This pull requests adds the following previews to `handle_image`, both commented out:
* DjVu, using `ddjvu`.
* ePub, using [epub-thumbnailer](https://github.com/marianosimone/epub-thumbnailer).
It also introduces a local variable `DEFAULT_SIZE`, controlling the size of previews that have to be rendered …
=> Previews for DjVu and ePub in scope.sh (commented out)

ranger/container/bookmarks.py, tests/ranger/container/test_bookmarks.py
Previously ranger was validating the bookmarks (whether they are existing
directories) when loading the bookmark file.  It caused the remote
filesystems like autofs to wake up unnecessarily and in general caused
more problems than solved.
Fixes #1365.
=> container.bookmarks: Remove invalid bookmarks only on access

ranger/config/commands.py
- Bug fix
- Terminal emulator and version: Terminator
- Python version: 3.7.2
- Locale: en_GB
When the directory at point has full-stops in it, rename_append would
put the point at the last period in the dir-name, as it would with a
file.  This commit addresses this issue.
=> rename_append: Use `rename` if point is on a directory

ranger/ext/vcs/svn.py
- Bug fix
- Operating system and version:  Arch linux 4.20.11-arch1-1-ARCH
- Terminal emulator and version: termite v14
- Python version: 3.7.2
When invoking svn status on a clean working copy, subversion returns an empty string, which later causes an error when trying to parse its status and therefore the vcs icons are not drawn.
This PR avoids that by skipping empty results.
I couldn't use the same approach as in git because subversion won't add the LF character to the end of the string so ```self._run(['status']).split('\n')[:-1]``` would cause the last path to be missing.
This fixes #1296
=> fix issue #1296

ranger/config/rc.conf, ranger/core/actions.py, ranger/core/loader.py
This PR is directly addressing #1473 . I've implemented a _dest_ argument for the built in _paste_ command.
- Debian GNU/Linux busterr/sid
- Urxvt 9.22
- Python 3.6.6 
- ranger-master 1.9.2  
I've just added one additional argument to the `paste` method in the `Actions` class. The given value gets passed to the `CopyLoader` object and if it is not `None` and given it is a proper path, the it will be used as destination path.  
Everything discussed in #1473 and several personal problems with ranger. I really wanted to be able to quickly copy/paste/cut files in some of my bookmarks. The most of the functionality can be implemented as custom function/plugin and the accompanying keybindings but the problem with the paste stays. …
=> Implementing destination argument for the built in paste command

ranger/config/commands.py, ranger/core/actions.py
This add a reset_previews command, which helps when switching preview_script
on-the-fly.
ranger version: ranger-master 1.9.2
Python version: 3.6.7 (default, Feb 28 2019, 08:33:23) [GCC 5.5.0]
Locale: en_GB.UTF-8
Add a new function 'reset_previews' to ranger/core/actions.py:
1. The previews are reset to {}
2. self.fm.ui.need_redraw is set to True
This new command means that ranger does not need a full reset when the preview_script is changed.
See: https://github.com/ranger/ranger/issues/1483 for more info.
The preview_script has been set multiple times on-the-fly to different viewer scripts, and it appears to work well.
There are no affect on other areas that I am aware of.
=> Add a reset_previews command

ranger/gui/widgets/statusbar.py
- Bug fix
- Python version: 3.7.2
- Ranger version/commit: 6944156c3150f1fe4ad8d7d75965e17b72017cc0
- Locale: 
Simply ignore the invalid mtime value instead of trying to convert it
to a date, which fails.
See #1020 
Tried a FUSE filesystem that sometimes reports invalid mtimes.
=> Fix crash when entering directories with invalid mtimes

ranger/gui/widgets/statusbar.py
The remote filesystems report their mount path as the mount root even if they contain other mount points on the remote side.
Fixes #1505.
=> Calculate the free space on remote filesystems correctly

ranger/container/fsobject.py
Some comics are pdf files and therefore treated as documents, comic
archives like cbz aren't. This brings the two in line.
=> Treat comics as documents

doc/ranger.1, doc/ranger.pod, ranger/config/rc.conf, ranger/container/fsobject.py, ranger/core/linemode.py, ranger/ext/human_readable.py
@Vifon @toonn As per our discussion in #1364. I did not include the leap year section.
- Operating system and version: 4.19.4-arch1-1-ARCH  (Antergos)
- Terminal emulator and version: kitty 0.13.1 with tmux 2.8
- Python version: Python version: 3.7.1 (default, Oct 22 2018, 10:41:28) [GCC 8.2.1 20180831]                              
- Ranger version/commit: ranger version: ranger-master v1.9.2-78-g9cc6c451             
- Locale:  en_US.UTF-8  
See #1364 for details. 
Easier to read dates. 
`make test_pytest` PASS
`make test_pyflake8` PASS
<details><summary><code>make test_pylint</code> FAIL (seems unrelated)</summary>
<pre>
Running pylint...
pylint ./ranger/container ./ranger/api ./ranger/core ./ranger/gui ./ranger/colorschemes ./ranger/ext …
=> Add human readable date linemodes

ranger/config/commands.py
`not self.quantifier` excluded `0`, which is a perfectly valid
quantifier for `chmod`.
=> Fix quantifier check

ranger/data/scope.sh
Our setup for syntax highlighting in `scope.sh` was actively preventing
people's configuration for `highlight` from working. Now
`HIGHLIGHT_OPTIONS` takes precendence over the default and over the
`HIGHLIGHT_STYLE` environment variable.
Users can specify `HIGHLIGHT_STYLE` or `PYGMENTIZE_STYLE` enviroment
variables now to customize the syntax coloring theme without having to
edit *and keep up to date* `scope.sh`.
Fixes #1556
=> Scope no longer interferes with users' configuration

ranger/config/commands.py
- Terminal emulator and version: urxvt v9.22
- Python version: 3.7.0
- Ranger version/commit: ranger-master 1.9.2
Make bulkrename create missing destination directories
For example:
- Test directory:
```
$ ls -l 
1
2
3
```
- `:bulkrename` input:
```
test/1
2.txt
test/3.txt
```
- `:bulkrename` output script:
```
mkdir -vp -- test
mv -vi -- 1 test/1
mv -vi -- 2 2.txt
mv -vi -- 3 test/3.txt
```
- Resulting test directory:
```
ls -1R
.:
2.txt
test
./test:
1
3.txt
```
https://github.com/ranger/ranger/issues/963
Tested with Python 2 and 3.
=> Make bulkrename create destination directories (fixes #963)

ranger/data/mime.types
Python's mimetypes module apparently doesn't know about Monkey's Audio.
=> Add ape extension to mime.types

ranger/__init__.py
Fixes ranger calling `git describe` in cwd instead of ranger's source directory.
- Bug fix
- Operating system and version: archlinux 5.1.6-arch1-1-ARCH x86_64
- Terminal emulator and version: rxvt-unicode
- Python version: 3.7.3
- Ranger version/commit: ranger-master v1.9.2-234-g2dad0b8
This patch changes the `version_helper()` function in `__init__.py` to specify the cwd parameter as ranger's source directory.
Ranger currently calls `git describe` in cwd, leading to git error messages as described in https://github.com/ranger/ranger/issues/1577.
This patch passes `make test`, but I highly doubt it would break anything.
=> fix to call git describe in ranger's source directory

ranger/__init__.py
Need to catch `stderr` in a `PIPE` to avoid showing it to the user.
=> Stop git errors before they reach user

README.md
The more effectively to tempt `mc` users over to the dark side with : )
As mentioned in #1557, the multi-pane viewmode may be a more important feature than we give it credit for, hence, let's highlight it in the README.
=> Add a multi-pane screenshot to the README

ranger/ext/img_display.py
- Bug fix
- Improvement
See #1565.
*No tests were added.*
Prevent lingering file handles to the working directory of ranger when the first image is being previewed with w3m or ueberzug.
Fixes #1565 .
1. Mount a drive.
2. Open a new ranger process at (or cd to it) `/data_win10/Images`, which contains a single image file that was then being previewed by ueberzug.
3. `gh` in ranger to change the working dir to $HOME (ranger must remain open)
4. attempt to unmount / show lsof output
```
~/code/ranger ∇ sudo mount /data_win10
[sudo] password for fichte:
~/code/ranger ∇ ls -l /proc/27442/cwd
lrwxrwxrwx 0 fichte 2019-05-22 21:56 /proc/27442/cwd -> /data_win10/Images/Screenshots
~/code/ranger Ξ lsof /data_win10
COMMAND    PID   USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
ueberzug 27442 fichte  cwd …
```
=> Open image displaying subprocesses in safe workdir

ranger/gui/ui.py
KP_ENTER is only treated as newline by curses when Num Lock is on.
This, like anything involving Num Lock, is confusing and has therefore
been dealt with : )
Fixes #1568
=> Treat KP_ENTER the same regardless of Num Lock state

ranger/config/rifle.conf
Adds support for opening `epub` ebook files and `cbr/cbz` comicbook files with [`zathura`](https://github.com/pwmt/zathura).
Adds support for opening `epub` ebook files with `mupdf`.
- Operating system and version: Arch Linux; latest `-Syu` as of a few hours ago
- Terminal emulator and version: urxvt 9.22
- Python version: Python 3.7.3
- Ranger version/commit: ranger 1.9.2
Adds an entry for `zathura` to `rifle.conf`’s list of epub/cbr/cbz viewers.
Adds an entry for `mupdf` to `rifle.conf`'s list of epub viewers.
Zathura is a minimalist document viewer. It also supports epub and cbr/cbz files. epub is a common ebook format and cbr/cbz is a common comicbook format. This adds support built-in support for opening such files with …
=> zathura has been added as epub viewer

README.md
Hello,
The goal of this PR is to make the wiki more visible.
To do this, I've added a 'Going further' section at the end of `README.md` which mentions the [Official User Guide](https://github.com/ranger/ranger/wiki/Official-User-Guide), the [FAQ](https://github.com/ranger/ranger/wiki/FAQ%3A-Frequently-Asked-Questions), and the [wiki](https://github.com/ranger/ranger/wiki).  The FAQ isn't too furnished, but having it on `README.md` might incentivise us to improve it.
This was prompted by two things:
1. Based on my experience, people do not have the habit of checking out the wiki on GitHub pages, especially when they're not used to GitHub.
2. People often ask us questions about the image-previews over at `#ranger`, even though we're addressing the common issues in the wiki.  This seems to …
=> Make the wiki more visible

README.md
Hi,
Since hut has added the logo to [github.io](https://ranger.github.io/) page, we might as well add it to the top of our `README.md`.
Note that I'm using the same version that hut picked, which isn't the same as the one that is in `ranger-assets`.  This is why I'm using an external URL rather than adding the logo to the repo.  I'd rather hold off until we have a final version for the logo.
HTH.
=> Add logo at the top of README.md

Makefile
Having the date in the manpage depend on a user's locale and their
timezone makes the format change depending on which user generates it.
=> Switch manpage date from locale dependent to ISO UTC

.github/workflows/python.yml, .github/workflows/shellcheck.yml, ranger/data/scope.sh
Run our python tests and shellcheck in seperate workflows only when
relevant files are changed, respectively python files or `scope.sh`.
This tests with one extra version of python, 3.7.
GitHub's version of shellcheck seems to be missing a few flags. So we
download the latest stable version, 0.7.0 currently.
=> Add GitHub Actions ci

ranger/core/actions.py
When files get deleted, ranger now shows the deleted files' names in the status line, which is also possible to see later with <kbd>W</kbd>.
Some users expect `:delete` to say more than "Deleting!", rightly so.
No new tests needed.
=> core.actions: Log which files were deleted

doc/ranger.desktop
One of the Debian patches our `ranger.desktop` to include `Keywords`. I
figure if we apply this downstream need not bother and many people can
benefit.
=> Apply debian patch 0004 desktop entry lacks keywords

.github/workflows/doctest.yml, .github/workflows/py37.yml, .github/workflows/python.yml
Some of our tests fail because the GH Actions runners don't provide a terminfo database which ncurses needs. I've seperated the troublesome tests so we still get *some* feedback.
=> Seperate failing GH Actions

ranger/gui/widgets/statusbar.py
Fixes #1704.
The last commit message shown in the status bar is now truncated at 70 characters so it doesn't get hidden entirely if it's ridiculously long. I chose 70 characters as a pretty common limit.
=> Truncate the VCS commit message

ranger/config/commands.py, ranger/config/rc.conf, ranger/config/rifle.conf
`trash-cli` is usually used to remove file using a traditional "Trash bin" pattern with a possible undo and all these fancy whistles. Since some of our users would like such a support (#1699), let's add it.
=> Add a trash-cli support to the default rifle.conf

doc/ranger.1, doc/ranger.pod, examples/rc_emacs.conf, ranger/config/rc.conf, ranger/container/settings.py, ranger/gui/widgets/statusbar.py
Previously it was hardcoded as 50, let's make it easy to change for the user.
Improves upon #1705.
Related to #1704.
=> Add a configurable max VCS message length

ranger/config/commands.py
`cunmap` definitely won't be missed because it was buggy. I'd expect the other two to be even less missed.
I considered writing a decorator for deprecation because the code is repetitive but imo it should be removed in the *next* version after 1.9.3 so it shouldn't matter much.
Fixes #1698
=> Deprecate c/p/tunmap in favor of unc/p/tmap

ranger/config/commands.py
This adds wl-copy to the list of executables checked for clipboard support.
This adds `wl-copy` to the list of clipboard executables checked. It is checked before xsel/xclip under the assumption that if it is installed, then the user is running wayland. (A better check could include checking for WAYLAND_DISPLAY as well before using it; can add that if reviewers would prefer.)
This is required to use the copy-to-clipboard functionality in ranger under wayland.
=> add wl-clipboard support

ranger/config/rifle.conf, ranger/core/runner.py, ranger/ext/rifle.py
Expands `X` and `t` flags to support Wayland as a graphical environment (to add to the current checks for darwin and Xorg).
fixes #1635
- Breaking changes (backwards compatible, but the XW condition in rifle.conf is not backwards compatible
~This introduces the extra `W` condition. This checks if
`WAYLAND_DISPLAY` is set. It can be used with the `X` condition to mean
"X or Wayland is available". For example:~
```
ext x?html?, has firefox,          XW, flag f = firefox -- "$@"
ext test, has example,          W = example -- "$@"
ext x?html?, has chromium,       X, flag f = chromium -- "$@"
```
This is to support users running wayland. Users may be running pure
wayland (without xwayland available), or with xwayland for running
X-only applications within …
=> support wayland condition for rifle

ranger/container/fsobject.py
- Bug fix
- Operating system and version: Manjaro Linux 5.2.21
- Terminal emulator and version: XTERM
- Python version: 3.7.4
- Ranger version/commit:  Ranger-Master 1.9.2
- Locale: de_DE.UTF8
Made small changes to the get_permission_string() Method in fsobject.py. 
Changed the if-block so that if a directory which is also a link will be treated as a such and will get the 'l'-flag just like in a Terminal context.
Symlink directorys where shown as "d" in the permissions in the bottom left of Ranger.
Changes were applied and Ranger 
as far as I can tell, None.
=> fixing issue 1673

Makefile
Every time a manpage is updated both manpages are rebuilt using
`make man`, this is annoying because you have to checkout the manpage
that didn't change every time you do this. The new rules properly use
`make`'s features to only rebuild a manpage *if* necessary.
=> Split PHONY man target into seperate real targets

ranger/core/fm.py, ranger/ext/img_display.py
Added ImageDisplayer registry
- Terminal emulator and version: st 0.7
- Python version: 3.7.4
- Ranger version/commit: ranger-master v1.9.2-319-g3b8a3252/86281229606e147870b365d7aff445e394883674
- Locale: en_us
- commit 3b8a32522ebb392a29759ec814947db048592f2e
I've added a registry for ImageDisplayers, to manage a growing number of sub-classes and to allow users to add their own sub-classes. Each ImageDisplayer can register with a key by using the register_image_displayer class decorator. These classes can then be used by setting preview_images_method accordingly in their rc.conf.
For example, in commands.py:
```
from ranger.ext.img_display import register_image_displayer, ImageDisplayer …
```
=> added registry for ImageDisplayer classes

ranger/core/actions.py
I changed the default `dest` for paste to the value that's used if
`None` were passed to the `CopyLoader`, i.e., `self.thistab.path`,
because the current directory was bypassing the `isdir()` check
otherwise.
Fixes #1660
=> Check current dir exists when pasting

ranger/ext/rifle.py
After #1341 the action IDs displayed by the UI were inconsistent with the actual numbers used by rifle.  It was caused by the `ask` action being skipped entirely (including incrementing the ID) but only in the UI.
This is a hotfix that makes the hidden `ask` action to still take up a number (usually (always?) 0) and thus keeping the numbering consistent.  Bad side effect: sometimes the counting starts with 1 instead of 0 but for a time being let's choose a small inconsistency over a BIG one.
=> Hotfix for an off-by-one in rifle

ranger/data/mime.types
Have some `.opus` files which aren't recognized by ranger as being media. `.opus` is one of the accepted extensions for opus encoded audio in an ogg container and seems to be the trend to distinguish it from vorbis encoded audio in an ogg container (`.ogg`).
=> Add .opus as extension for audio/ogg

ranger/config/rifle.conf
Rifle serves a similar purpose to `xdg-open` on Linux and `open` on
macOS. We fall back to those so users can enjoy their xdg and other
configuration from rifle.
=> Add generic openers for linux and mac

ranger/data/mime.types
- Operating system and version: Linux (NixOS unstable)
Ranger now identifies WebP images as having the MIME type of `image/webp`.
WebP is new enough that Python's `mimetypes.guess_type` did not identify them, which meant the `.image` property on `FileSystemObject` was incorrectly set to `False`. This breaks functionality like the `open_all_images` setting.
Ranger now identifies `.webp` files as images, and `open_all_images` with sxiv works as expected on directories full of WebP images.
=> Add image/webp to known mimetypes

ranger/ext/img_display.py
Fixes image previews in iTerm2 when using Python3. See #1600 for some additional information.
- Bug fix
Operating system and version:
MacOS Sierra - 10.12.6
Terminal emulator and version:
iTerm2 - Build 3.3.0beta12
Python version:
Python 3.6.4 
Type "help", "copyright", "credits" or "license" for more information.
Ranger version/commit: 1.9.2
I compared the output in the function that generates the image, of Python2 and Python3 versions of ranger. I found that the output of the `_encode_base_image` returned a bytestring. This was being string interpolated into a string. In Python2, this will result in an implicit conversion of the bytestring to a unicode string and will be interpolated into a unicode string. In Python3, this will result in the representation of the bytestring interpolated …
=> Fix Python3 image preview in iTerm2

ranger/core/actions.py, ranger/core/main.py
`--clean` is incredibly useful when testing contributions to `scope.sh`
among other things but some (most?) previews require the cache to
function.
As a compromise every invocation using `--clean` will create a temporary
cache directory.
Fixes #1783
=> Restore access to a preview cache in clean mode

README.md, doc/ranger.1, doc/ranger.pod
The man page was missing the various optional dependencies for previews.
I revised and then copied the list from the `README.md`.
Fixes #1781
=> Add list of optional deps to man page

ranger/config/rc.conf
I forgot to remove the setting from `rc.conf` when I merged the behavior
into the `update_title` setting.
=> Drop the update_icon_title setting

ranger/data/mime.types, ranger/data/scope.sh
Direct Stream Digital/Transfer (`.dsf`) files have MIME type
`application/octet-stream` but they're audio so `audio/something` is
more useful for rifle.
Scope also runs `mediainfo` and `exiftool` for miscellaneous `audio/*`
files but we can't match on MIME type here so I added a similar clause
in `handle_extension`.
=> Add Direct Stream Digital/Transfer to mime types

ranger/config/commands.py
Fuzzy tab completion was dropping the entire valid prefix instead of
showing the path relative to the current directory.
```
/ $ cd usr/sh<tab>
/ $ cd share/      # `usr/` is dropped because it's already a valid
/ $ cd usr/share/  # Proper result with the fix.
```
Fixes #1792
=> Fix fuzzy tab completion when prefix is valid dir

ranger/config/commands.py
Currently, the separator is appended to the tab matching result only if exactly one matching directory has been found.
If multiple matching directories have been found, the separator is omitted.
This makes quick multi-level tab completion a bit complicated if multiple matches are present because one has to enter the separator manually after cycling through the matches before typing the match pattern for the next directory level.
This pull request proposes to append the separator also for multiple results.
The drawback, however, is that the following scenario is not possible anymore:
1. Use autocompletion with multiple results, for example `cd /l` + `tab`
2. choose directory by entering `/`
3. Press tab in order to cycle through directories in the chosen directory without a pattern
Hence, …
=> cd: append sep to results of tab matching also for multiple results

ranger/config/commands.py
Surrogates aren't allowed in the UTF-8 encoding but filenames can
contain any bytes. We need to pass the surrogates literally because
otherwise `mv` won't be renaming the right files.
=> Pass surrogates when listing files for bulkrename

ranger/data/mime.types, ranger/data/scope.sh
Add `.dff` extension to `mime.types`.
Add `dff|wv|wvc` to `handle_extension` because they're not caught by the
`audio/*)` clause in `handle_mime`.
=> Add extensions not previously covered by scope.sh

ranger/colorschemes/default.py
We were doubling up bold and BRIGHT for the name of the selected file in
the titlebar.
=> Fix white text on white background in titlebar

README.md, doc/ranger.pod, ranger/data/scope.sh
This Pull Request leverages the free OpenSCAD software (available in a repository near you) to generate preview images for 3D model files. The two main file formats that most people will use are STL and DXF. And also include off, scad and csg.
=> add support for 3D files including STL and DXF

ranger/ext/img_display.py
- Bug fix
- Operating system and version: Arch Linux x86_64
- Terminal emulator and version: terminator 1.91
- Python version: 3.7.4
- Ranger version/commit: ranger-master v1.9.2-390-g482fced9
W3MImageDisplayer now redraws the window using `self.fm.ui.win.redrawwin()` when clearing the preview. 
Users with terminal emulators based off of GNOME Terminal (such as terminator) will encounter an issue when using W3MImagePreview (#1071, #859) that results in a previous preview being drawn over rather than replaced as intended.
TravisCI build passed, pylint passed with 9.87/10 (no change). Does not seem to affect other areas of the codebase.
=> Fixed issue with W3MImgPreview not clearing previous image

doc/ranger.1, doc/ranger.pod, ranger/config/rc.conf, ranger/container/settings.py, ranger/gui/ui.py
- Bug fix
- Operating system and version: Manjaro Linux 5.2.21-1
- Terminal emulator and version: urxvt
- Python version: Python 3.7.4
- Ranger version/commit: 1.9.20 Master
- Locale: de_DE-UTF.8
Applying the proposed Tmux renaming window fix from issue #1739.
Change fixes a problem that the current Tmux window does not get rename even if the option is set.
Tests have been run. Very small changes to the codebase.
=> applying proposed tmux renaming fix

ranger/core/main.py
The `--clean` mode was leaving semi-temporary traces in /tmp. On long-lived systems it could easily clutter /tmp and didn't feel nice in general.
=> Cleanup the temporary cache directory in the --clean mode

doc/rifle.pod
Add note to rifle manpage that it will only read one config file. In response to #1825.
- Open to rewording the sentence/adding more information.
- Also, not sure how to update the manpage itself from the `.pod` file.
My original issue  #1825 came about because I assumed that `rifle.conf` behaved exactly like `ranger.conf`. I assumed I'd only need to add settings that differ from the default `rifle.conf` rather than needing my `~/.config/ranger/rifle.conf` to contain *all* the rules required.
=> Add note in rifle manpage of  rifle.conf reading behavior

doc/ranger.1, doc/ranger.pod, ranger/config/rifle.conf
- Improvement
Change the fallback trash location to use the correct environment variable and
ranger's default data directory. Update the man page to reflect the change.
Fixes #1848
I can't get the tests to run properly. I only manually changed `rifle.conf` and `ranger.pod` and ran `make man`.
=> Fix trash location

ranger/gui/ui.py
Fixes 'FileNotFound' if `screen` is not available on the system.
- Bug fix
- Terminal emulator and version: Fish 3.0.2
- Python version: 3.8.1
- Ranger version/commit: ranger 1.9.3
Change `screen` to be invoked via a shell so it doesn't raise unexpected error type. 
https://github.com/ranger/ranger/issues/1805
=> Fix `FileNotFoundError` on startup

doc/howto-publish-a-release.md, setup.py
After years of supporting both, I think it'll be wise to let the venerable distutils rest.  Even the Python docs recommend setuptools over using distutils directly.
- Breaking changes
`distutils` don't support many of the pretty crucial features such as,
well, uninstalling.  For years I've been opposed to letting them go,
because I didn't like how `setuptools` throws an error when installing
out of `PYTHONPATH` but currently I think my use case wasn't justified
enough.  Let's do this.
I've installed the `ranger-fm` package from `setup.py` into a fresh
virtualenv.
=> Fully migrate from distutils to setuptools

Makefile
Since `python` is supposed to always point to a python 2.x executable
and python 2.x is no longer supported by the PSF, we should try to
install with `python3` by default and fall back to `python` and then
`python2`.
Fixes #2006
=> Default to python3 at install, fall back to python

ranger/config/commands.py
The flags a bulkrename command passed to the command runner were fixed
to `w`, which means "wait for an enter keypress." Now it's possible to
pass whichever flags you want. Passing any flag overrides the default so
if you still want the confirmation you need to explicitly pass `w`.
Fixes #2002
=> Implement passing of flags for :bulkrename

ranger/core/tab.py
I can't reproduce the problems with <Right> and I don't see anything in
the commit that could've caused them in the first place tbh. The issue
this introduces keeps coming up so I'm verting the original change.
Fixes #1655
This reverts commit 11549e2c0c73a8a0bb543801af4e134b3e076095.
=> Revert "Revert "ranger <path> can select files""

ranger/config/commands.py, ranger/core/actions.py, ranger/core/filter_stack.py, ranger/core/main.py, ranger/ext/img_display.py
As FichteFoll rightly pointed outin #1840, python 2.6 did *not* support
implicit format spec numbering for positional arguments.
This commit brings the code back in line with our promise that it is
compatible with python 2.6.
I used the following patterns to grep for occurences:
- '"\{\}"'
- '"\{:.*\}"'
- "'\{\}'"
- "'\{:.*\}'"
=> Py26 does not support implicit format spec numbering

ranger/config/rc.conf
Neglected to add drawing of bookmarks to the mapping that allows pasting
the contents of the copybuffer to a bookmark's path.
Brought to my attention by discussion in #1277.
=> Add bookmark drawing to the paste to bookmark map

ranger/core/actions.py
The performance hit is negligible. File name lengths are usually 255
bytes at minimum (except for FAT, but a SHA-1 digest is truncated too).
An attack on the ranger cache based on hash collisions is probably
fairly unlikely but preventing it is almost free.
This should be merged soon after #1838 because both these PRs change the
cache hashes and can therefore cause generation of previews that have
been cached before, wasting some disk space.
=> Switch from SHA-1 to SHA-512 for the cache

ranger/core/actions.py
This allows the use of symlinks to prevent copying files to the cache.
Fixes #1837
=> Allow equal mtime for cached previews

ranger/config/rifle.conf
Add the Rust extension `.rs` to the list of programming languages to
match editor and pager because it is erroneously guessed as being
`application/rls-services+xml`.
=> Add rust to programming languages for rifle

ranger/__init__.py, ranger/config/commands.py, ranger/container/file.py, ranger/container/tags.py, ranger/core/actions.py, ranger/core/fm.py, ranger/core/loader.py, ranger/core/main.py, ranger/core/tab.py, ranger/ext/img_display.py, ranger/ext/keybinding_parser.py, ranger/ext/widestring.py, ranger/gui/bar.py, ranger/gui/widgets/console.py
We check whether we're running python 2 or 3 in many places. In some
places we do more specific version checks but with the new `PY3`
constant modeled after `six` this code should be slightly more readable.
=> Factor out python 3 version checking

ranger/colorschemes/default.py, ranger/colorschemes/jungle.py, ranger/colorschemes/snow.py, ranger/gui/context.py, ranger/gui/widgets/browsercolumn.py
Changes the default color for line numbers to differ from the file's
color to the terminal's base foreground color in the default theme.
Green in the jungle theme and bold and/or bright in the snow theme.
Fixes #1906
This means people can customize the color for line numbers in their colorschemes now.
I wasn't sure whether and how the solarized colorscheme should be updated.
=> Implement a line_number context for colorschemes

ranger/config/commands.py
`:mkdir` creates directories recursively like `mkdir -p`.
`:touch` failed when parent directories didn't exist, for convenience
and consistency it now creates missing directories recursively.
Fixes #1998
=> :touch create missing directories

ranger/ext/shutil_generatorized.py
`WindowsError` has been merged into `OSError` so we can no longer rely
on it for disambiguation. This means a previously silent error on
Windows regarding the copying of file access times will no longer be
silent.
=> Remove WindowsError

ranger/core/actions.py
The hashes from python's hashlib only support objects that implement the
buffer API. Bytes objects (python 2 string, python 3 string.encode())
are such objects.
Passing fields from a stat object to a hash directly caused crashes
whenever ranger checked for an image preview.
Fixes #2032
=> Hashlib requires objects implementing the buffer API

ranger/core/actions.py
Python 2 implicitly decodes strings as ASCII or the system's default
encoding before encoding a string to bytes. This results in problems if
the string already contains characters outside the ASCII range (> 127).
I reintroduced this bug thinking encoding a string in both python 2 and
3 would be harmless.
Actually swapped the order of the inode and the path which should've
happened in the previous commit.
Fixes #2054
=> Fix unicode decode issues in py2

ranger/core/tab.py, ranger/gui/widgets/browsercolumn.py
Tabs only remembered the pointer of their browsercolumn. This lead to
erroneous rendering of the selection. By additionally keeping track of
the object which is pointed at we can restore the remembered pointer
even when sorting or (un)filtering completely invalidates the remembered
index.
Fixes #1511
Fixes #1995
=> Selection in multipane viewmode was misleading

ranger/core/actions.py
A typo crept into the encoding of paths used for the hashes of cached
images. The error handler "backslashescape" doesn't exist, it should've
been "backslashreplace."
Fixes #2119
=> Fix encoding of cached filenames

ranger/config/rifle.conf
Adds support for more filetypes/apps in the rifle default config. These are things I use in my own config that I felt could be useful to others too. Found them while merging new changes from the upstream rifle.conf into mine ( https://github.com/swalladge/dotfiles/commit/e4b62ed6c277a94ae28cef3f54d1cf7f6fb73e65 ). Summary of changes:
- audacity
- firefox dev edition
- scribus projects
- sc (cli spreadsheet editor)
- krita image editor
- fix bug where wine is erroneously displayed if not installed
These are simple config additions to support more filetypes out-of-the-box for rifle. Simply convenience.
Does not affect the codebase. The added rules in rifle.conf should be inspected to ensure they don't conflict or clobber existing rules.
=> Add support for more apps in rifle default config

doc/rifle.1, doc/rifle.pod, examples/rifle_different_file_opener.conf, ranger/config/rifle.conf
Allow `PAGER` environment variable to contain spaces for options/flags. This PR is the same as: https://github.com/ranger/ranger/pull/128
- Bug fix
- Operating system and version:
Nixos 20.03.3191.504f993df9a (Markhor)
alacritty 0.4.3
- Python version:
Python 3.7.6 
- Ranger version/commit: 1.9.3 
See the commit message: https://github.com/ranger/ranger/commit/a8105b082f94729669d0509f07c98aa566c0278f .
Some Linux distros like Nixos define the default PAGER as a `"<binary> <flags...>"`. The default ranger configuration doesn't work with distros having that configuration.
Additionally, this change is consistent with the lack of quoting for `EDITOR` in the default `rifle.conf` (https://github.com/ranger/ranger/blob/master/ranger/config/r …
=> Allow `PAGER` environment variable to contain spaces for options/flags

ranger/gui/widgets/statusbar.py
- Bug fix for #1880 
- Operating system and version: Manjaro Linux 
- Terminal emulator and version: xfce4-terminal 0.8.9.2
- Python version: 3.8.3 (default, May 17 2020, 18:15:42) [GCC 10.1.0]
- Ranger version/commit: ranger-master 
- Locale: en_AU.UTF-8
Bound `tab.change` and `setopt.viewmode` signals to StatusBar widget `request_redraw`
Added a new test to `def draw()` that enforces current column to match browser `main_column`
Solves the bug of the Status bar getting locked to an old directory when switching tabs in multipane mode and on returning to miller mode.
Ran all existing tests successfully. 
This only affects the statusbar when multipane mode is used.
=> Test for and follow tab changes in multipane mode

ranger/ext/img_display.py
- Bug fix
- Operating system and version: Arch Linux x86_64
- Terminal emulator and version: kitty 0.14.6
- Python version: Python 3.8.0
- Ranger version/commit: 1.9.2.389.g28f3d014-1
preview_id was assigned negative id, which is not valid kitty id
#1603
=> Fix ranger freeze after shell command during kitty preview

ranger/config/rc.conf
The maps without explicit target only changed user permissions. The
chmod utility changes all permissions when the target's omitted. This
brings both more in line.
Fixes #2161
=> Change chmod maps

Makefile
`\s` is a GNU-ism not found in BSD sed. Both implementations support the
equivalent `[:blank:]` character class.
=> Change sed invocation for POSIX compliance

ranger/container/tags.py
Report errors if tag file does not exist
A non-existent tag file leads to an opaque crash without indication to
the user of what went wrong as in #2200. These errors are now reported
through ranger's notify mechanism.
The tag file is no longer created conditionally on `__init__`, only upon
writing saving tags. This changes the behavior somewhat in that an empty
"tagged" file should never be created.
Only write tags if they might've changed
=> Tags errors

ranger/data/scope.sh
- Bug fix
- Operating system and version: `Ubuntu 20.04 LTS` & `macOS Catalina`
- Terminal emulator and version: `Gnome-Terminal` / `iTerm 2`
- Python version: `Python 3.8` & `Python 2.7.18`
- Ranger version/commit: `master`
- Locale: `en_US.utf8`
Add `from __future__ import print_function` to `python -c` command.
The preview for Zip file cannot show properly if `/usr/bin/python` is `Python 2`.
=> Fix python versions compatibility in scope.sh

ranger/core/tab.py
When we try type ```scout -aestf``` (flag 'f' is important), we get "IndexError: list index out of range".
- Bug fix
- Operating system and version: Linux
- Terminal emulator and version: st
- Python version: 3.8.6 (default, Sep 30 2020, 04:00:38) [GCC 10.2.0]
- Ranger version/commit: ranger-master v1.9.3-146-g6fd49695
I just add new handler for IndexError, as toonn did it in #2071.
I many often get this error and I hate this.
I also think it may be relate with: #2086, #2136, #2173, #2125
=> Fix files index

doc/ranger.1, doc/ranger.pod, ranger/config/commands.py
- Operating system and version: Archlinux, 5.10.8-arch1-1
- Terminal emulator and version: st
- Python version: 3.9.1
- Ranger version/commit: ranger-master v1.9.3-174-g290c1f5f
Added '-s' flag for "console" command. It sets cursor position at index of special characters.
'%^' make some errors and '^&' look pretty and little logical.
#1914
And it's actully usefull feature.
=> Added -s flag for set position by char seq '^&'.

ranger/config/commands.py
- Bug fix
- Terminal emulator and version: rxvt-unicode 9.22-10
- Python version: Python 3.9.1
- Ranger version/commit: commit 6e78bbe3 (current master)
- Locale: en_US
Merge 6e78bbe39 introduced an option for :console to specify cursor position with
a sentinel character. Since then it doesn't actually insert the command if none
of the cursor position options are used, which is fixed here.
Steps to reproduce:
- Run the command `:console test`
Result on current master: the console input is empty, doesn't show the command "test".
Result with this change: the console shows the command "test". Cursor is positioned at the end.
Breaking change was introduced in merge commit 6e78bbe39 https://github.com/ranger/ranger/commit/6e78bbe39a5a5edecf6021788a6379 …
=> Fix empty console when using :console without position option

ranger/core/filter_stack.py, ranger/core/fm.py, ranger/ext/rifle.py
- Bug fix
Changes how `MimeTypes` objects are used and initialized in ranger and rifle. In both use cases, the same set of
mimetype files are read and added on top of the hardcoded defaults in the mimetypes python library:
1. Mimetype files set in system (python/mimetypes library installation)
2. The `data/mime.types` from ranger (standalone rifle remains exception here)
3. The `~/.mime.types` if it exists
This fixes issue #1744 (on my system at least).
The discussion in #1744 seems to suggest that mimetypes behavior varies across some variables (python version and/or
library versions and/or other system specs). So I guess in some configurations these changes can lead to loading the
same mimetype file multiple times, which is fine.
=> Fix mimetypes initialization #1744

ranger/core/main.py
Currently, ranger incorrectly handles file URI path arguments (does not open, reports *Inaccessible paths*). This is due to the URI prefix string in the code containing an extra slash (`file:///` instead of `file://`). This PR fixes that.
- Bug fix
- Operating system and version: Fedora 33
- Terminal emulator and version: rxvt-unicode v9.22
- Python version: 3.9.1
- Ranger version: 1.9.3
Please see #2265.
This PR fixes #2265.
Tested using `make test_py` as well as manually.
=> Fix file URI prefix

ranger/core/actions.py
On some systems (e.g. archlinuxarm) man is not installed by default, hit
'?' and 'm' will cause ranger crashed, showing:
AttributeError: 'NoneType' object has no attribute 'poll'.
- Bug fix
- Operating system and version: archlinuxarm, with kernel 5.8.0
- Terminal emulator and version: zsh 5.8
- Python version: 3.9.1
- Locale: zh_CN.UTF-8
Hit ? and m on archlinuxarm will cause ranger to crash.
I have tested it on archlinuxarm.
=> Fix crash if man is not installed when hit '?' and 'm'.

ranger/config/rifle.conf
- Operating system and version: Arch Linux 5.11.7-zen
- Terminal emulator and version: kitty
- Python version: 3.9.2
- Ranger version/commit: v1.9.3
This Pull request adds dart support in rifle.
when creating a new dart file, rifle didn't specially recognised [dart](https://dart.dev/overview) files, so added dart too in rifle.conf
=> dart support addition in rifle.conf

ranger/config/commands.py, ranger/core/fm.py
- Bug fix: This fixes #1798.
- Operating system and version: `Arch Linux, kernel 5.4.23-1-lts, last full pacman update at: 2020-03-05T08:20:22`
```
rxvt-unicode (urxvt) v9.22 - released: 2016-01-23
options: perl,xft,styles,combining,blink,iso14755,unicode3,encodings=eu+vn+jp+jp-ext+kr+zh+zh-ext,fade,transparent,tint,XIM,frills,selectionscrolling,wheel,slipwheel,cursorBlink,pointerBlank,scrollbars=plain+rxvt+NeXT+xterm
```
- Python version: `Python 3.8.1`
- Ranger version/commit: `v1.9.3-18-g081e7315` (output of `git describe HEAD`)
- Locale: `en_US.UTF-8`
(`make test_py` outputs is the same before and after the change)
(`make test_py` output is the same before and after the change)
The `execute()` method of the trash command (in …
=> Fix crashes when deleting to trash (#1798)

doc/ranger.1, doc/ranger.pod, ranger/gui/widgets/browsercolumn.py
A regression when implementing preview scrolling meant that clicking the preview no longer opens files.
I have fixed this regression but changed the original behavior to require a right click because the left click caused plenty of frustration by accidentally opening files when focusing the terminal window.
=> Clickable preview

ranger/ext/img_display.py
This fixes what TERMs are checked in relation to a tmux session and then apply the correct escape sequences for the URxvt and iterm backends
- Bug fix
- Terminal emulator and version: rxvt-unicode 9.26
- Python version: 3.9.5
- Locale: UTF-8
Previously, only the TERM value of `screen` was checked when performing image previews inside of tmux. This PR expands the possible values checked to include all(?) tmux TERM values.
My image previews weren't working with the urxvt backend inside of tmux :(
The image previews work inside of tmux now!
No tests run to be honest. This shouldn't impact anything, it's a pretty minor change.
=> Fix tmux image display for other possible TERMs

ranger/data/scope.sh
- Operating system and version: Arch Linux 5.12.11-arch1-1
- Terminal emulator and version: st 0.8.4
- Python version: 3.9.5-3
- Ranger version/commit: bff3c6b
- Locale: 
LANG=en_CA.UTF-8
LC_CTYPE="en_CA.UTF-8"
LC_NUMERIC="en_CA.UTF-8"
LC_TIME=en_DK.UTF-8
LC_COLLATE=C
LC_MONETARY="en_CA.UTF-8"
LC_MESSAGES="en_CA.UTF-8"
LC_PAPER="en_CA.UTF-8"
LC_NAME="en_CA.UTF-8"
LC_ADDRESS="en_CA.UTF-8"
LC_TELEPHONE="en_CA.UTF-8"
LC_MEASUREMENT="en_CA.UTF-8"
LC_IDENTIFICATION="en_CA.UTF-8"
LC_ALL=
Addresses wishes expressed in #2202:
If [mu](https://github.com/djcb/mu) is installed, displays the content of message/rfc822 in preview, cleared of all formatting tags.
Prior to the change, scope.sh had no way to deal with message/rfc822 and no preview was displayed.
In …
=> scope.sh: add mime handling for message/rfc822. This improves #2202.

ranger/config/commands.py
`wl-copy` used to take precedence over `xclip` and `xsel` but this can
cause problems. So let's try the other way around, maybe Wayland users
are less likely to have `xclip` and `xsel` installed than the other way
around.
Fixes #1861
=> commands: Change precedence of clipboard managers

.github/workflows/pylint.yml, .github/workflows/python.yml, .github/workflows/shellcheck.yml
My testing was flawed. The status checks seemed to work fine because the
builds were triggered on push in the same repo. But this doesn't work
across repos. So GH Actions having run to completion on someone's fork
doesn't give us the status checks we need. Therefore we want to run our
Actions on PRs too, that way they're run from the ranger repo as well
and the status checks should actually be informative.
One possible improvement is that we could duplicate the workflows we
want to run on PRs, that way we can drop all the things that don't
really matter for status checks from the version matrices. Otoh that
means we have pretty much duplicated workflows we need to keep in sync.
Thank you for your lack of abstractions, GH Actions 🙄
=> Actions: Add on pull_request again

ranger/ext/img_display.py, ranger/ext/popen23.py, ranger/ext/popen_forked.py, ranger/ext/rifle.py, ranger/ext/spawn.py, tests/pylint/py2_compat.py, tests/pylint/test_py2_compat.py
I've reverted the relevant with-statement transformations.
I also noticed that `with Popen():` isn't compatible with Python 2 so I added a wrapper and a pylint check to fix it and make sure it doesn't happen again.
=> Process forking was broken when satisfying pylint's consider-using-with

README.md, doc/ranger.1, ranger/data/scope.sh
- Operating system and version: Arch Linux 5.13.9-arch1-1
- Terminal emulator and version: Alacritty 0.9.0
- Python version: 3.9.6
Use ffmpeg to get embedded thumbnails. As far as I know this is only supported by mp4 videos. The code is commented out because it requires ffmpeg. It is placed before ffmpegthumbnailer because its thumbnails are likely more relevant.
I use youtube-dl and I like having the thumbnail because it is more useful than a random frame from 10% into the video. I use `--embed-thumbnail` when the video is mp4 to have less files. This lets me have image previews of the thumbnail.
I ran all the files in tests directory with python. I ran shellcheck on `scope.sh`
I will edit the wiki …
=> Use Embedded Thumbnails

ranger/core/actions.py
tabnew proxies to tab_new, tabclose proxies to tab_close, and so on.
Both forms (with and without underscore) remain available, the
underscore being the canonical ones.
See https://github.com/ranger/ranger/issues/2412
=> Make tab command names consistent with vim, closes #2412

examples/rc_emacs.conf, ranger/config/rc.conf
- Bug fix
- Operating system and version: macOS Catalina
- Terminal emulator and version: iTerm 2
- Python version: `3.9.6`
- Ranger version/commit: `master@209b8a`
- Locale: `en_US.UTF-8`
According to `du`'s manual page on macOS:
Command `du` does not compatible with option `--max-depth` and `--apparent-size` on BSD-based systems.
Change option `--max-depth` to `-d` and remove option `--apparent-size`.
None.
=> Fix command `du` on macOS

ranger/gui/displayable.py, ranger/gui/widgets/browsercolumn.py, ranger/gui/widgets/titlebar.py
- Operating system and version: Manjaro Linux x86_64
- Terminal emulator and version: Alacritty
- Python version: Python 3.9.6
- Locale: EN-US
This pull request is expanding the BIDI feature from a previous pull request, which enables correct display of file names and folders with Hebrew/Arabic characters to also work in the ranger title bar.
I have been using ranger for quite sometime now and the mishandle of Hebrew file names really began to annoy my eyes. This addition makes the experience of browsing over files in Hebrew a lot smoother for me.
I ran all of the python tests and verified the output.
=> Added support for Right-To-Left languages in the title bar

ranger/gui/ui.py
Made a mistake when merging #2201. If the "TMUX" key isn't in the
environment dictionary we'll get a KeyError. Providing an empty string
default should fix the problem.
I applied the same logic to the check for screen because TERM isn't
guaranteed to be in the environment either, though this verges os
malicious.
=> ui: Fix crash when TMUX not in environment

ranger/ext/img_display.py
fix #2423
This is the proposed solution. Moving the delay after self.process .
It needs some testing, i don't know if that breaks the "horizontal black bars" mitigation.
=> fix w3m method in 32bit

doc/ranger.1, doc/ranger.pod, ranger/config/commands.py, ranger/container/settings.py
- Bug fix
From the `setlocal` section of the man page:
```
path is a regular expression.  This means that "path=~/dl" applies to
all paths that start with ~/dl, e.g. ~/dl2 and ~/dl/foo. To avoid
this, use "path=~/dl$".
```
#1652 caused the `path` argument to be regex escaped. This commit
fixes that.
=> Make setlocal path=... argument a regex again

ranger/data/scope.sh
- Operating system and version: Arch Linux 5.13.10-arch1-1
- Terminal emulator and version: Konsole 21.08.1
- Python version: 3.9.7
This adds a clause to `scope.sh`'s mimetype switch statement for `application/x-executable`, `application/x-pie-executable`, and `application/x-sharedlib` to invoke `readelf -WCa`. This allows the user to view, among other things, the various sections of the executable, shared libraries it includes, and any symbols inside the file.
This allows users to see basic information about an ELF file from the command line, allowing users to see what functions an executable or library offers or relies on.
I'm also interested in a similar function for PE files, but I do not know of …
=> Adds a preview for ELF files using readelf

examples/rifle_sxiv.sh
Hi,
I have been using the sxiv-rifle script as a wrapper around sxiv for a
long while now. There's a couple changes that can be made to improve the
performance of it. On my system I was able to achieve a 25% performance
increase, benchmarked with time (0.005 vs 0.004).
First of all, inside listfiles() we don't need to call `dirname`. Since
we already have the absolute path, we can just use parameter expansion.
Secondly, we don't need to call printf inside abspath(), we can directly
set the value to `"$target"`. In fact we can go one step further and
offload no arguments checking and abspath() into one case statement.
P.S. It should be noted that although I've been using this script, I
however don't use ranger myself. I do assume that this should be fine
since the logic of the script is …
=> sxiv-rifle: add webp and performance improvement

HACKING.md
Hut no longer actively manages contributions so people should use Github
or the mailing list. Unfortunately we don't have a good setup for
PGP-based communication about security issues with all maintainers.
#2411 is what prompted this. They first sent an email to hut with a patch, adding some friction to the process.
=> HACKING: Drop hut's email and PGP key

doc/ranger.1, doc/ranger.pod
I detected a few hotkeys related to previews were mistakenly referred to in the manual. I hope this commit fixes it, but please double check.
=> Fix some hotkeys referred in the manual

ranger/data/scope.sh
See #2518. The ods and odp filetypes do not appear to be supported by pandoc. When odt2txt is not installed on the system, ods and odp file previews are run via pandoc. Pandoc, however, does not seem to support these files, and memory usage may increase uncontrollably.
This fix changes `scope.sh` to handle ods and odp files separately from OpenOffice odt files, eliminating the pandoc fallback to preview.
- Bug fix
-  Operating system and version: 5.15.6-2-MANJARO
-  Terminal emulator and version: kitty 0.23.1
-  Python version: Python version: 3.9.9 (main, Nov 20 2021, 21:30:06) [GCC 11.1.0]
-  Ranger version/commit: aur/ranger-git 1.9.3.26.g4bb83b37-1 (+146 0.04) (Installed: 1.9.3.387.g7e6a0aa6-1)
-  Locale: en_US.UTF-8
This fix changes `scope.sh` to handle ods and odp files separately …
=> Disabled pandoc file previews for ods/odp files to fix possible memory issues

README.md, doc/ranger.1, doc/ranger.pod, ranger/data/scope.sh
- Operating system and version: Pop!_OS 21.04 (based on Ubuntu)
- Terminal emulator and version: Terminator 2.1.0 (zsh 5.8 + tmux 3.1c)
- Python version: 3.9.5
- **NOTE:** The tests in `master` don't pass for me even without these changes, but no *additional* tests fail with these changes ~~(I'm not even sure if `scope.sh` has tests)~~
`rsvg-convert` works much more reliably for SVGs than ImageMagick's `convert`, which freezes with large SVGs (seems to convert formats first, and resize only after that), and can drop out text during the conversion. Support for SVGs isn't great in ImageMagick, since it's a raster graphics program.
`rsvg-convert` only supports conversion to PNG. The image preview works …
=> Add rsvg-convert for SVG previews

README.md, ranger/data/scope.sh
Breaking out jupyter notebooks from the json preview. The new preview uses `jupyter nbconvert` to output markdown and then `bat` to color it properly. Fallback without bat is available as is the previous json viewers in case `nbconvert` is missing.
- Locale: 
Makes jupyter notebooks readable in preview (the jsons are basically useless really).
I tested it on my computer and should not affect codebase.
new preview:
original preview:
=> better textual preview for jupyter notebooks

ranger/core/runner.py, ranger/ext/accumulator.py, ranger/gui/colorscheme.py, tests/pylint/test_py2_compat.py
PyLint has grown stricter yet. The changes are minor and we don't care about the exact line positions of the py2_compat errors so we're ignoring those.
=> PyLint: Deal with new lints

ranger/gui/widgets/browsercolumn.py
This fixes the width of files being off whenever a line number with an extra digit appears,
shifting the width one item too early, shifting relative line numbers more than necessary and a trailing space on the file size.
@NoSuck, I created this PR because you did not seem interested in continuing discussion/development on PR #2346 after @markus-bauer's comments. Thank you for bringing the issue to my attention! A review of this PR would be really welcome.
@markus-bauer, thank you for digging into this issue.  I'd appreciate a review. I considered your suggestion to replace `line_numbers` with `linum_text_len` in the key but it seemed like improperly overloading the meaning of that variable and I don't really see any harm in making this key a little bigger.
In the last commit I did add a …
=> Fix width calculation when line numbers are enabled

.github/workflows/pylint.yml, requirements.txt
As of 2.14.0 PyLint dropped the python3 port checker. This means many of
the features we want to disable, because we need syntax compatible with
Python 2 are gone and we can no longer disable the checks.
=> pylint: Pin to 2.13.9

ranger/gui/widgets/browsercolumn.py
It looks like the separator is being unexpectedly flattened by the list
concatenation.
Fixes: #2641
=> browsercolumn: Fix separator depth

.github/workflows/python.yml
Not all versions of Python we test with support installing the PyLint
version we need and the tests don't require PyLint anyway, so no need to
install any version of PyLint at all.
=> GHActions: Refrain from installing PyLint for tests

ranger/gui/widgets/browsercolumn.py
When predisplay_right is empty (which is the case when vcs_aware is
off), the separator should be omitted. This fixes the error introduced
by my last commit.
=> browsercolumn: Only add the separator when needed

ranger/config/rifle.conf
Unrelevant here.
I added viewnior as one of the default image openers.
Note: I added it even above the SVG's one because viewnior supports svg images.
If you use viewnior as image viewer and have no other one installed, which was my case, the image opens with gimp, which, it goes without saying, is not practical.
=> Add viewnior in rifle config

tests/manpage_completion_test.py
On systems that do not put Python at `/usr/bin/python` the original shebang line causes a cryptic error from make saying the file doesn't exist but it's actually the interpreter not being found. `/usr/bin/env` should be more pervasive and respect venvs and such.
=> manpage_completion_test: Change interpreter directive

ranger/config/rc.conf
In general, it is possible for du to emit output and still return failure.
Previously, this resulted in duplicate entries on systems that support both long
and short options (since both parts of the AND-OR are run).
Here, we prevent duplicates by only having one outputting du invocation, at the
cost of extra assumptions:
- /dev/null is readable and length 0.
- Short options are always supported.
---
- Bug fix
- Operating system and version: Linux 5.17.0-1-amd64
- Terminal emulator and version: xterm 372-1
- Python version: 3.10
- Ranger version/commit: ranger-master 391f061cb0b0cfa8266c0651f2a6d948f22e01dd
- Locale: ugh
See above.
See above. Pull #2427 relevant.
`make test` with dependencies prescribed by `HACKING.md`.
=> Check for --apparent-size before invoking on cwd.

ranger/gui/ui.py
We call `decode` on the result of calls to `tigetstr` but that returns
`None` if the current terminfo does not support the capability we ask
for.
Fixes #2587
=> ui: Guard terminal capabalities

examples/rifle_sxiv.sh
- Bug fix
(Ran shellcheck and it doesn't report any problems)
Imlib2 v1.8.0 adds loaders for svg, heif and avif.
ico support seems to have been there for a while.
add all these to known image extensions.
originally we checked the extension to make sure the argument is an
image to avoid edge cases like this:
./a        # is a dir
./a.jpg
where running `rifle_sxiv a` would open up `a.jpg` instead of `a` the
directory.
however the is_img function was not correct as it would fail on upper
case extensions, such as `a.JPG`.
instead of doing extension check in two places, now we just have a
is_img_extension() function which checks for extension
case-insensitively via grep.
in short:
* this checks the extension case-insensitively
* reduces some code …
=> rifle_sxiv: more correct fallback and add more img support.

ranger/ext/rifle.py
Currently `rifle` completely ignores the exit status of the commands it runs, even if it does wait for them (it's obviously not viable otherwise). This patch makes `rifle(1)` (the commandline application) exit with the same status the command did, and makes `rifle` the module raise `subprocess.CalledProcessError`, so it's displayed in the `ranger` status line.
As it stands, it was impossible to inspect whether the commands executed by `rifle` were successful or not.
The errors are no longer swallowed and instead are reported back in the manner described above. If someone relied on them being swallowed, it might break their use case (but maybe for the better).
=> Acknowledge and report the exit status of the rifle'd commands

ranger/data/scope.sh
Replaced use of tabs with spaces and removed trailing white-space to be consistent with the rest of the file.
=> Remove trailing whitespace and mixed indentation

CONTRIBUTING.md
- Bug fix
info on security-relevant bugs has been removed from HACKING.md, yet CONTRIBUTING.md refers to it. This change removes the "dead link" in CONTRIBUTING.md.
=> Remove outdated information on security-relevant bugs

ranger/ext/img_display.py, ranger/ext/rifle.py
Accidentally introduced names that were introduced in Python 3. TimeoutExpired inherits from SubprocessError, which isn't in Python2 either, which inherits from Exception. Way too broad but not really another option.
DEVNULL was also introduced to the subprocess module later. Passing in `os.devnull` should be more or less equivalent in behavior.
=> Fix Python 2 support related to Subprocess

ranger/ext/img_display.py
Kitty version 0.26.0 stopped removing temporary files used in the Kitty Image Protocol unless their full path contains the string "tty-graphics-protocol," so we need to adapt to the new behavior.
By using a subdirectory of the directory used for temporary files with the appropriate name, Kitty should again delete the temporary PNGs we generate. An added benefit of using a subdirectory is avoiding cluttering up the directory for temporary files. This subdirectory is not cleaned up by Ranger and will remain as an empty directory (if previews work correctly) until removed by other means.
Fixes #2699
=> img_display: Restore cleanup of Kitty tempfiles

ranger/ext/img_display.py
Even if image is not in RGB or RGBA format, it could still contain
transparency information.
I used the "transparency" key in the image info dict, see documentation here: https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html
Basically this key only exists for some formats in some modes, when the image contains transparency. I didn't test any formats besides a rudimentary test of palette mode .png; this change may also affect .eps, .gif, .gd, .xpm.
- Bug fix
- Operating system and version:  Arch
- Terminal emulator and version: kitty 0.25.2
- Python version: 3.10.5
- Ranger version/commit: fcf44f6f12506fa0096cb6468de6a2706bbfaf51
Fixes: https://github.com/ranger/ranger/issues/2690
I ran the tests and got a 9.99/10 reported failure rate; but AFAICT …
=> Fix image display for palette images with transparency

ranger/core/linemode.py
.. because when the cumulative size of a directory has not yet been
determined, its size is actually the number of direct children.
So displaying byte suffixes in that case is incorrect.
=> Make display of directory size in linemodes less misleading

ranger/ext/shutil_generatorized.py
- Bug fix
When copying folders that contain dangling symlinks, ranger throws an error message, although the copying itself seems to succeed. This change fixes it. Tried to fix the pylint complaints, not sure about the other tests.
=> Fix "Loader work process failed" error when copying dangling symlinks

ranger/config/commands.py, ranger/container/directory.py, ranger/core/filter_stack.py
I've removed the original filtering mechanism ranger used to use, and replaced it with a thin compatibility layer that utilizes the newer filter stack mechanism. While I was at it, I also added live previews for the `:filter_stack add name` command just like the ones we have in `:filter`.
- Operating system and version: NixOS 22.11
- Terminal emulator and version: Alacritty 0.11.0
- Python version: 3.10.9
- Ranger version/commit: N/A
Assuming no explicit filter stack manipulation occurs, the semantics should be the same as before. If filter stack is being actively used, the compatibility layer either edits the topmost filter (if it's a name-based one), or adds a new element to the filter stack (all the other cases). Both such a …
=> Remove the legacy filename filters, replace them with a compatibility layer utilizing the filter stack

ranger/core/linemode.py
- Bug fix
- Operating system and version: N/A
- Terminal emulator and version: N/A
- Python version: Python 3.10.9 and Python 2.7.18.6
- Ranger version/commit: N/A
- Locale: N/A
The previous solution used the ABCMeta metaclass directly as the ABC non-meta class didn't exist in Python 2.
Python 2 and 3 have different syntax for metaclasses.  The one used by Python 2 doesn't work on Python 3 but is not an error either.  The one used by Python 3 is an error in Python 2.  We used to use the Python 2 syntax while acknowledging it merely doesn't do anything on Python 3.
The regular class ABC allows to avoid using the metaclass syntax at all, but it's only available in Python 3.  This solution implements it on our side (using the Python 2 metaclass syntax) if it's not available, but otherwise …
=> Fix the ABC checks on Python 3

ranger/config/commands.py
Added an option to the `:cd` command.
Using `:cd -e $HOME` will do the expected thing.
- Operating system and version: x86_64 GNU/Linux 6.2.8-arch1-1 (Arch Linux)
- Terminal emulator and version: kitty 0.27.1
- Python version: Python 3.10.10
- Ranger version/commit: ranger-master v1.9.3-604-g8875ad2f
I have many files and directories in my environment, like `$XRESOURCES`, `$XINITRC`, `$PYTHONPATH`,...
A simple `cd` into or select of that dir/file was previously not possible.
Now if I want to hop into my `$NVIMRC`, I can do just that with `cd -e $NVIMRC`
`cd -e $HOME/.config` works; changes directory correctly
`cd -e $XINITRC` works; selects file
`cd -e $TEST_DIR` works, where `$TEST_DIR` contains spaces.
The `cd` command now …
=> Support Expansion Of Environment Variables in cd command

ranger/ext/get_executables.py
Not every system has a `/proc` file system. We could catch the error but it is simpler to check `platform.release()`. This string contains `WSL2` for WSL version 2 but the only common substring for version 1 is lower case `microsoft`. On Windows this string should simply contain a major version number and not include that substring.
Fixes #2815
=> get_executables: Use platform instead of reading /proc

ranger/container/directory.py
Pylint flagged a nested max call as redundant but it was a false positive. However, the nested max call materialized a generator as a list and prepended `-1` because the function errors on an empty argument. Instead of nesting a max call we can drop the nesting and prepend the current value instead of passing it as a separate argument.
Fixes #2812
=> directory: Fix max call in mtimelevel

.github/workflows/other.yml, .github/workflows/pr.yml, .github/workflows/pylint.yml, .github/workflows/pypy.yml, .github/workflows/shellcheck.yml
Change CI to run conditionally without remaining pending
Using the built-in paths filter means Actions will not be run at all.
When they are set as "required checks" on PRs that means they will be
marked as pending forever. This is confusing for contributors and means
maintainers need to keep in mind when checks should actually complete or
not.
Using the paths-filter Action means we can use conditional execution of
steps, which results in things being marked as skipped, rather than
pending. This should make everything a bit less confusing.
Some tests that are only run on push events, mostly for the master
branch, still use the built-in path filtering. These aren't used as
required checks so they aren't as front and center.
One unfortunate consequence of the change is that more Action runs …
=> Unconfuse CI

ranger/core/linemode.py, ranger/ext/abc.py
It shouldn't be tied to the linemode module. Now it can be reused anywhere just as easily.
@toonn, please verify if this is the correct place. I don't have a strong opinion about it being inside `ranger.ext`, I just happened to put it in there.
=> Move the ABC compat wrapper to a separate file

README.md, doc/ranger.1, doc/ranger.pod, doc/rifle.1, ranger/config/rc.conf, ranger/container/settings.py, ranger/core/actions.py, ranger/ext/img_display.py, ranger/ext/popen23.py, ranger/ext/which.py
Fixes #723; Replaces #2234.
- Operating system and version: Generic GNU/Linux; macOS
- Terminal emulator and version: GNOME Terminal (latest Git commit) + VTE from the latest Git commit; mlterm 3.9.2; iTerm2
- Python version: CPython 3.11.1 and 2.7.16
- Ranger version/commit: N/A
- Locale: N/A
Implements an image preview module for SIXEL-capable terminals.
Properly clears preview area (VTE-ready).
#2234 provides a PoC implementation of a SIXEL image previewer.
It however did not dispose of expired images properly, which turns out to be an issue in some implementations (namely VTE).
SIXEL support is to be stabilized in the next release of VTE and will soon hit major Linux distributions such as Ubuntu, so it might be high time to finally get this done. …
=> SIXEL image previewer

ranger/data/scope.sh
ImageMagick requires a large amount of memory to process DjVu files and is run on anything with a MIME type matching `image/*`. By enabling the special case for DjVu files by default, we either use `ddjvu` or we exit instead of trying to run them through ImageMagick. Preventing this from happening.
Fixes #2366
=> scope.sh: Enable DjVu previews by default

ranger/ext/img_display.py
- Bug fix: Fixes #2883.
- Terminal emulator and version: vscode 1.80+ integrated terminal
- Python version: 3.10
With `preview_images_method iterm2` being set, vscode terminal does not show images. This is due to ranger wrongly sending the size of the base64 encoded content, instead of the byte size of the original file/data.
- `set preview_images_method iterm2` in conf file
- open integrated terminal in vscode
- run ranger
- navigate to folder with images
- images now show up
Vscode terminal will still refuse to show an image that creates a rather big sequence (>20MB, again a security/sanity check). Here it might make sense to do an interim resizing with PIL if available. (not part of this PR)
=> report file byte size in IIP

ranger/data/mime.types
Type `text/x-shellscript` to align with `file(1)` behavior.
No type added for JSON files because they officially have the `application/json` type.
Added several programming language extensions with type `text/plain` this agrees with `file(1)` for most. Two exceptions are `.rs`, which `file(1)` assigns `text/x-c` and is less than ideal, and `.tsx` which `file(1)` assigns `text/x-c++` and is even further removed.
Fixes #1804
This addresses most of the requests. `.gro` doesn't seem very common so I left it out.
=> mime.types: Add common requests

README.md
This adds the liberapay donation badge to the README.
I had to put the "latest package version" badge from 3 lines into 1, otherwise the github markdown renderer would add a linked whitespace with a blue underline between the two badges, which looked terrible.
=> Add liberapay donation badge

ranger/gui/ui.py
- Bug fix
- Terminal emulator and version: Alacritty 0.12.2
- Python version: 3.11.5
- Ranger version/commit: 136416c
- I did not run spellcheck `HACKING` was not clear which tool to use specifically
fixes #2873
Before ranger used to crash with `update_title=true` setting when trying to display a non-existent directory.
The reason was a call to `UI.fm.thisdir.path` while `UI.fm.thisdir == None` when ranger is pointing to a non-existent directory, invalidating the path attribute.
This PR checks if `UI.fm.thisdir` is None and makes sure `WM_NAME` shows `ranger:not accessible` (same as the ranger UI).
fix crashing issue detailed in #2873 
`make test_py` has been run successfully. I was not sure which spellchecker to get, …
=> fix #2873 WM_NAME now shows "not accessible" in non-existent directories

doc/ranger.1, doc/ranger.pod
- Operating system and version: Ubuntu 22.04 LTS
- Terminal emulator and version: Gnome Shell 42.9
- Python version: 3.10.12
- Ranger version/commit: 38bb8901004b75a407ffee4b9e176bc0a436cb15
- Locale: en_US
Fixed inconsistency in ranger documentation where it was stated that commanding 'linemode humanreadablesizemtime' changed the linemode to display human readable modification time and file size, but the correct command for this is 'linemode sizehumanreadablemtime'
Found the issue when I tried to follow documentation to set the default line mode. Realized the issue and figured I should make this change since it makes the documentation accurate to what the software actually does and will likely help future documentation readers in the future save some …
=> Linemode option documentation fix

README.md
The release neglected to bump the version in the README.
Since we're considering changing forges, switching to forge-agnostic URLs for the homepage and assets makes it more future-proof.
Replace the Travis badge with a GHActions badge.
Consolidate some style changes for the header of the README.
=> README: Update version, forge-agnostic URL and center logo

ranger/gui/ui.py
NCurses errors when `endwin()` is called twice in a row without the window being refreshed.
Runner suspends the window (calling `endwin()` indirectly) and uses  `initialize` to resume the curses window. The latter was originally envisioned as more of a one-item setup and only refreshes the window the first time it is called. Refreshing unconditionally avoids the problem.
Fixes #2934
Closes #2935
Fixes #3000
Fixes #3005
=> Adapt to NCurses endwin() error behavior

ranger/gui/ansi.py, ranger/gui/widgets/browsercolumn.py
- Breaking changes
- Operating system and version: Ubuntu 20.04 LTS
- Terminal emulator and version: GNOME Terminal
- Python version: `3.9.6`
- Ranger version/commit: `master` 
- Locale: `en_US.UTF-8`
Enable ANSI escape codes in browser columns. Closes #2349.
See https://github.com/ranger/ranger/issues/2349#issue-912723347 and alexanderjeurissen/ranger_devicons#23.
The existing tests `make test` and the visual test in the demo below.
Demo using [`devicons`](https://github.com/alexanderjeurissen/ranger_devicons) linemode with a random icon color:
```python
@ranger.api.register_linemode
class DevIconsLinemode(ranger.core.linemode.LinemodeBase):
name = "devicons"
uses_metadata = False
def filetitle(self, file, metadata):
icon = devicon(file)
if …
```
=> Feat: ANSI escape codes support for browsercolumn

.github/workflows/pypy.yml
Pypy 2.7 can only run Python 2.7 compatible Pylint and that effectively enforces a completely different linting standard. We can't satisfy both old and new Pylints so let's simply avoid running it altogether unless it's recent enough.
The only Pylint check that's really important is the one run for CPython 3. The version specified here, `3.3.1`, will have to manually be bumped if the Pylint versions for CPython 3 and Pypy 3 diverge sufficiently.
=> Avoid running older Pylint with Pypy

ranger/config/rifle.conf, ranger/data/mime.types
I've opened an issue for it: https://github.com/ranger/ranger/issues/3010
- Bug fix
- OS: Linux tfed-laptop 6.6.47-1-MANJARO `#1` SMP PREEMPT_DYNAMIC Mon Aug 19 09:51:26 UTC 2024 x86_64 GNU/Linux
- terminal: xfce4-terminal 1.1.3 (Xfce 4.18)
- Python version: 3.12.5 (main, Aug  9 2024, 08:20:41) [GCC 14.2.1 20240805]
- `I've got a local ranger git package` 
- ranger version: ranger-master v1.9.3-730-gbd9b37fa
- Ranger version/commit: bd9b37faee9748798f3970468bd0d1dedbf0e99f (the latest one)
I add `.nim` file-type in support due to #3010 issue
ranger (meaning rifle) doesn't want to open `.nim` from `l` and `Right` keys
because he thinks that `nim` stands for aNIMation, and not for Nim Programming Language
I haven't made much testes. …
=> Fixed mistooks of nim scripts as a video aNIMations in rifle.conf

ranger/config/rifle.conf
We prefer IINA over mpv as it's a native macOS app that uses libmpv as its backend. The `iina` command is provided by Homebrew Cask and the Nix package rather than upstream.
- Operating system and version: macOS 15
=> Add IINA to rifle.conf

doc/ranger.pod, ranger/config/commands.py, ranger/config/rc.conf, ranger/container/settings.py
Novel option "confirm_on_trash" is similar to option "confirm_on_delete", but for the "trash" action.
Default value for this option is "like_delete" for backwards compatibility.
- Operating system and version: Debian Trixie
- Terminal emulator and version: Xterm(395)
- Python version: 3.12.7 (main, Nov  8 2024, 17:55:36) [GCC 14.2.0]
- Ranger version/commit: ranger-master v1.9.3-731-gd97b6fc1
Didn't run "make man", as pod2man seems not to work well on my installation.
Trashing and deleting a file are completely different actions in terms of safety: one wants ranger to ask for confirmation when deleting whereas ranger should not ask for confirmation when trashing.  This option allows the user to enable this.
Of course, please feel …
=> Add option confirm_on_trash

README.md, doc/ranger.pod, ranger/config/rc.conf, ranger/config/rifle.conf, ranger/ext/img_display.py
Rather than checking `$TERM` to determine Kitty image protocol support, we can [query the terminal itself](https://sw.kovidgoyal.net/kitty/graphics-protocol/#querying-support-and-available-transmission-mediums). This means we will never need a list of supported terminals, and any new ones that add support will Just Work™.
Also, we add support for auto-detecting Ghostty in `rifle.conf`, just because that's not worth opening a whole new PR for.
Resolves #3035.
Currently, the Kitty image protocol is enabled only if `$TERM` contains `kitty`. That ain't gonna cut it, now that support for the protocol is being more widely implemented.
~~Currently, `make test` is broken (see #2976).~~ *Fixed now, and all tests pass!*
These changes have also been tested …
=> Properly auto-detect support for Kitty image previews

ranger/container/bookmarks.py, ranger/container/fsobject.py
- Operating system and version:  popOS 22.04
- Terminal emulator and version:  alacritty 0.14.0-dev (fd1a3cc7)
- Python version: 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]
- Ranger version/commit:  ranger-master
While loading saved bookmarks, we check if the path starts with `~` if it does then we replace the first occurrence of `~` with the current home directory.
This fixes #3032 
Manual tests were conducted with various edge cases to ensure the changes doesn't break anything.
=> add: support for tilde in bookmarks

ranger/config/commands.py, ranger/config/rc.conf
Add `:unnarrow` functionality to disable `:narrow` mode even if files are selected.
Implemented using a default argument for :narrow that defaults to True.
- Operating system and version: FreeBSD 14.2-p3 and macOS Sonoma 14.7.4 (23H420)
- Terminal emulator and version: iTerm2 Build 3.15.3
- Python version: Python 3.11.11 (FreeBSD) and Python 3.13.3 (macOS Homebrew)
- Ranger version/commit: `master/b31db0` 
- Locale:  `en_US.UTF-8`
This patch adds a new command alias `:unnarrow` which disables `:narrow` functionality. If narrow is not enabled, it has no effect.
There is no easy way to disable narrow without unselecting files. This command will allow the user to do that.
`make test` has been run successfully on FreeBSD and macOS.
Apart from adding a …
=> add :unnarrow to disable :narrow mode

ranger/core/actions.py, ranger/gui/widgets/view_base.py
The screen is now cleared at the appropriate time. The command info is cleared when the cmd line is cleared.
=> fixed bug with command info staying

ranger/ext/img_display.py
In [ueber-devel/ueberzug#26](https://github.com/ueber-devel/ueberzug/pull/26) Ueberzug stopped accepting `\` escape characters in input file names.
We should simply pass along the original filename rather than replace non-ASCII characters with `\uXXXX` escape sequences.
=> img_display: Avoid unicode escape sequences for Ueberzug input
