ranger/ranger

ranger/config/commands.py
=> Modified cd command to select original file, when following links.

ranger/config/commands.py
As "mkdir -p", e.g. :mkdir dir1/dir2/dir3
=> config.commands: added ability to create multilevel directories

ranger/config/rc.conf, ranger/container/directory.py
Some people requested this feature so I went ahead and implemented it.
=> container.directory: added sorting by file extension

ranger/config/commands.py
=> config.commands: bulkrename works with `:flat -1`

doc/ranger.1, doc/ranger.pod
I've added the manpage sections discussed on the IRC channel recently. Feel free to remove some of it as there is some redundancy.
=> doc/ranger.1: added some information about the config file loading process

ranger/core/actions.py
This way the different representation of the same path are treated in the same way.
=> core.actions: tab_switch uses realpath

ranger/config/rifle.conf
Hello,
there is a PDF viewer called qpdfview. I added this one to rifle.conf
Greetings
bastorran
=> add qpdfview to rifle.conf

ranger/gui/context.py, ranger/gui/widgets/statusbar.py
Additionally I've removed the leading space from the filter indicator and added it to the front of the right side of the statusbar as a separate element.
=> :flat statusbar indicator added

ranger/config/rifle.conf
This fixes, for instance, my problem with djvu files opened by image viewers. It also might be welcome for other possible "image-documents" types.  But I'm not sure, maybe there is a better way to cope with it.
=> Fix: djvu files are being opened with image viewers

ranger/config/commands.py, ranger/core/loader.py
fixed typo in rename
added recursive checking to move, rename, and delete; refactored previos code
bugfix: moved recursive tag checking for delete to commands.py
Fixes #118
=> added tag management for rename, delete, bulkrename, and moving of files

examples/plugin_linemode.py, examples/rc_emacs.conf, ranger/config/commands.py, ranger/config/rc.conf, ranger/container/directory.py, ranger/container/fsobject.py, ranger/core/linemode.py
The usage of file.basename could lead to some issues with :flat.
=> Replaced file.basename with file.relative_path where appropriate.

ranger/gui/widgets/statusbar.py
Fixes #327
Thanks: Dennis Bliefernicht @ http://stackoverflow.com/questions/51658/cross-platform-space-remaining-on-volume-using-python
=> Report free disk space correctly on Mac OS X

ranger/container/directory.py
If I understood it correctly, then this should fix issue #259.
=> Broken hidden file selection

examples/plugin_ipc.py
I have added a new example plugin which allows to control ranger from the external scripts.
=> added examples/plugin_ipc.py

ranger/container/fsobject.py, ranger/container/settings.py, ranger/ext/vcs/svn.py, ranger/ext/vcs/vcs.py
Implemented initial Subversion VCS support for Ranger. Based it off of the Hg support. Seems to work well, feedback welcome.
=> Implemented Subversion VCS support.

ranger/config/rifle.conf
Added qutebrowser web browser to rifle.conf
https://github.com/The-Compiler/qutebrowser
=> integration of qutebrowser web browser

ranger/core/fm.py
[imv](https://github.com/eXeC64/imv) now supports sxiv-like 'start-at' option.
This adds imv support for the **open_all_images** option.
=> open_all_images support for imv

examples/plugin_pmount.py
Since many people requested this functionality, I went ahead and implemented it...
=> pmount plugin for easy mounting

ranger/api/commands.py, ranger/config/commands.py, ranger/config/commands_sample.py, ranger/gui/widgets/console.py
shift-tab functionality for scout etc.
=> commands.py: Pass number to tab()

ranger/config/commands.py, ranger/core/actions.py
Fixes #458.
It also fixes the issue where fm.copy_buffer was not properly cleaned up
when fm.delete was called with arguments.
=> :delete refactoring

ranger/core/actions.py
=> Restore :delete backward compatiblity

ranger/config/commands.py
I checked that it was working by:
- Creating a bookmark on a folder
- Renaming the folder
- Accessing the bookmark and checking that it got me to the right place
=> bookmarks: fix issue #447 Bookmarks aren't updated on renaming

.gitignore, Makefile, ranger/container/bookmarks.py, ranger/container/history.py, ranger/core/actions.py, tests/ranger/container/test_bookmarks.py, tests/ranger/container/test_container.py
- Adds py.test tests for bookmarks and history. This will allow to easily switch to `collections.deque` for history without regression.
- Also do some minor renaming / removing unused methods
- Add the tests to the makefile (now requires py.test to run)
=> Add py.test tests structure and tests for bookmarks and history

AUTHORS, ranger/colorschemes/default.py, ranger/config/commands.py, ranger/container/directory.py, ranger/container/fsobject.py, ranger/ext/vcs/__init__.py, ranger/ext/vcs/bzr.py, ranger/ext/vcs/git.py, ranger/ext/vcs/hg.py, ranger/ext/vcs/svn.py, ranger/ext/vcs/vcs.py, ranger/gui/context.py, ranger/gui/ui.py, ranger/gui/widgets/__init__.py, ranger/gui/widgets/browsercolumn.py, ranger/gui/widgets/browserview.py, ranger/gui/widgets/statusbar.py
Features:
- Separate thread making main thread more responsive
- Continuous updates based on idle_delay setting
- All repo data is stored in root `Directory` object
- Lazy subrepo initialization: Only root's data is initialized
- Only update already initialized `Directory` objects
- Added symbol for local repository
- Fixes #209, #348, #375, #380
Currently only git backend is fully working. Improvements to hg, bzr, svn backends are needed. Help is welcome.
I'll squash all commits before merge.
=> Refactor VCS extension

ranger/config/rc.conf, ranger/container/settings.py, ranger/core/tab.py
=> Configurable ability to clear all filters in folders on navigation

ranger/config/rc.conf, ranger/core/actions.py
=> Added toggle mode for cut/copy actions.

ranger/data/scope.sh
=> Support 256 colours if available

doc/ranger.pod, ranger/core/actions.py
Application:
map x source %confdir/rc.conf
=> Add %confdir macro

ranger/config/rifle.conf
This adds pqiv to the default rifle.conf for images.
=> Add pqiv to rifle.conf

ranger/container/fsobject.py, ranger/core/linemode.py
=> Add ModificationTimeLinemode

ranger/core/actions.py
... Am I the only one crazy enough to have rifle entries in the double digits?
=> Program indices now line up nicely.

ranger/ext/img_display.py
This should resolve #548. So far, I've been unable to get the problem to recur after making this change.
=> Handle broken w3m-img pipe on exit

doc/ranger.1, doc/ranger.pod, ranger/config/rc.conf, ranger/container/settings.py, ranger/gui/widgets/browsercolumn.py
As requested in #489, add line numbers in main column.  Supports normal and relative variants.
=> add line numbers in main column

ranger/config/commands.py
=> Command chaining now handles semicolon whitespace.

ranger/ext/vcs/bzr.py, ranger/ext/vcs/git.py, ranger/ext/vcs/hg.py, ranger/ext/vcs/svn.py, ranger/ext/vcs/vcs.py
=> VCS: git: Fix log output containing control characters, Fixes #641

ranger/gui/widgets/statusbar.py
=> fix issue #679: Statusbar percentage crashes on python 2.6.6

ranger/container/fsobject.py, ranger/core/linemode.py, ranger/ext/spawn.py, ranger/ext/vcs/vcs.py
Rename `spawn` to `check_output`
Mimic `subprocess.check_output`
=> ext.spawn: Refactor

examples/plugin_fasd_add.py
This is a small plugin that log opened files to fasd.
=> added examples/plugin_fasd_log.py

ranger/container/settings.py
Every setting will be initialized with the first allowed value. Alternative to #602.
=> Sane setting fallback values

ranger/gui/ui.py
This is a fix for #228 and duplicate #685. The problem is that whenever you set the title, `automatic-rename` gets disabled:
```
automatic-rename [on | off]
Control automatic window renaming.  When this
setting is enabled, tmux will rename the window
automatically using the format specified by
automatic-rename-format.  This flag is automati‐
cally disabled for an individual window when a
name is specified at creation with new-window or
new-session, or later with rename-window, or with
a terminal escape sequence.
```
This PR detects the state of the option when ranger starts, and restores this when quiting.
=> Tmux title reset

ranger/ext/img_display.py
A cleanup of the new urxvt-based image previews. Depends on #682 and #687.
=> Cleanup the urxvt image previews

ranger/core/actions.py, ranger/core/fm.py, ranger/core/main.py
Possible issue:  using set() to get unique paths, which changes order of chosen files.
=> Proposed implementation of feature request #667

doc/ranger.1, doc/ranger.pod, doc/rifle.1, ranger/config/rc.conf, ranger/container/settings.py, ranger/core/actions.py, ranger/core/fm.py, ranger/ext/direction.py
- Improvement/feature implementation (ref feature request #176 )
- uses already existing `cycle()` method of `Direction`
- adds new `wrap_scroll` boolean setting (default false)
Useful feature that has been requested in the past, and was already partially implemented.
=> implement setting for wrap scrolling

examples/rc_emacs.conf, ranger/config/commands.py, ranger/container/directory.py, ranger/gui/widgets/statusbar.py
The feature name is derived from https://www.gnu.org/software/emacs/manual/html_node/emacs/Narrowing.html
Closes #867.
=> Add the :narrow command

ranger/gui/widgets/view_base.py
=> Reset hint color

ranger/data/mime.types
Add mime type recognize .weba files
=> New mime type: audio/webm

ranger/data/mime.types, ranger/gui/widgets/console.py
- Bug fix
- Locale: 
Enable scrolling of questions given in console mode that exceed the
terminal width
=> Movement for long questions

Makefile
Fix typo in Makefile.
Signed-off-by: Zabielski, Kamil <kamil.zabielski@outlook.com>
```
Darwin localnet 17.2.0 Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64
```
- Terminal emulator and version: Terminal.app
```
Python 3.6.3
```
```
ranger-stable 1.8.1
Python 2.7.10 (default, Jul 15 2017, 17:16:57) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```
- Locale: 
```
LC_CTYPE=UTF-8
```
Small improvement of Makefile.
There is no reason to execute shell command for echoing.
Building improvement
I does not affect the codebase at all.
=> Fix missing `@` character

README.md
=> README: Make it clear that --copy-config takes an argument

.pylintrc, ranger/api/commands.py, ranger/config/commands.py, ranger/container/directory.py, ranger/core/actions.py, ranger/core/metadata.py, ranger/core/tab.py, ranger/ext/accumulator.py, ranger/ext/next_available_filename.py, ranger/ext/rifle.py, ranger/ext/signals.py, ranger/ext/vcs/vcs.py, ranger/ext/widestring.py, ranger/gui/bar.py, ranger/gui/ui.py
Treat it as a hotfix for the CI / work in progress. Some of these functions really could use a refactoring (or removal: I found at least two that are not called anywhere).
=>  Fix the "inconsistent-return-statements" Pylint warning

ranger/gui/widgets/console.py
- Bug fix
Fix issue #852
- Locale: 
Fixes bug with incorrect cursor movement in console mode for
text length greater than terminal width
=> Fix issue #852 incorrect cursor movement

CHANGELOG.md
Update CHANGELOG v1.9.0beta1 in order to include the improvement made to the logging system.
In particular the work that I've submitted through PR #725.
=> Update CHANGELOG v1.9.0beta1: mention logs handling improovement

ranger/core/actions.py
- Operating system and version: Linux 4.14.15-1-ARCH #1 SMP PREEMPT Tue Jan 23 21:49:25 UTC 2018 x86_64 GNU/Linux
- Terminal emulator and version: XTerm(330)
- Python version: 3.6.4
- Ranger version/commit: ced74b92d12dfa2abb06cccae3af7df0ab05cc81
- Locale: ja_JP.utf8
Without this, there is no way to reload the “tagged” file.
You can now tag paths using external utilities (e.g. a feh action).
freenode#ranger @ 2018-02-09.
All.
They don't.
=> Reload tags on reset

ranger/core/actions.py
- Operating system and version: Linux 4.14.15-1-ARCH #1 SMP PREEMPT Tue Jan 23 21:49:25 UTC 2018 x86_64 GNU/Linux
- Terminal emulator and version: XTerm(330)
- Python version: Python 3.6.4
- Ranger version/commit: bfe1dbafaec8d79cb77fca93d4daa5a98e2cbf29
- Locale: ja_JP.utf8
The `tag` parameter has been added to `tag_add` and `tag_remove`.
Previously, it was not possible to specify a tag through `fm.tag_add` or `fm.tag_remove`.  I noticed the issue because the `tag_toggle` command is insufficient for using IPC in a remote-like, broadcast fashion (as toggling would result in different output depending on the number of open ranger processes).
=> Fully encompass tag_toggle

doc/ranger.pod, ranger/config/rc.conf, ranger/container/settings.py, ranger/core/actions.py, ranger/ext/img_display.py
=> Add a small delay before calling w3m to mitigate the display corruption problem

.travis.yml, Pipfile, Pipfile.lock
I'm so sorry about the accidental push to master when experimenting with the pipenv builds on Travis! And with such a silly typo...
=> Fix the Travis build

Makefile
`which python3` will likely show the latest version of python installed on system, so, it should go the first.
I think, it's not necessary to write all of possible versions of python. You can just use `which python3 || which python`...
=> Update PYTHON variable

ranger/data/scope.sh
Implemented archive previews in scope.sh. It uses the first alphabetically
sorted image file in the archive or falls back to text-based preview methods if
there are none.
=> Implement image previewing for archive files

doc/ranger.1, doc/ranger.pod, ranger/config/rc.conf, ranger/core/actions.py
=> Add a bindable action for scrolling the file preview

ranger/core/loader.py
ranger/core/loader.py:
CommandLoader.generate() gets text for preview panel from scope.sh
as the blocks of byrearray (max 512 bytes). This blocks immediately
decoded to utf-8. But in case when muli-byte unicode characters is
present they may be split and python will can't correctly to decode
it. For example: b'abc\xd0', b'\x9a...'
b'\xd0\x9a' - is cyrillic letter 'K' and it can't be decoded
separately (UnicodeDecodeError occurs).
So, received data blocks (bytearrays) must be collected and
only after that decoded as one whole byrearray.
Fixes #906
Fixes #967
Fixes #1166
=> Broken preview of highlighted text with Python3

README.md
- Terminal emulator and version: Terminator 1.91
- Python version: 3.7.1
- Locale: en_GB
Various syntactic fixups in README.md.
I forgot to remove a newline in a previous PR, and was *kindly* asked by the maintainers to review the rest of the page as penance. I hope this will placate them.
=> Syntactic fixups in README.md

ranger/data/scope.sh
Just fixed a small typo in `scope.sh`
=> Fix little typo

ranger/ext/img_display.py
=> Fix the Kitty previews in fullscreen mode

README.md
- Bug fix (Documentation issue)
=> changed pip command ; package is called ranger-fm

ranger/core/actions.py, ranger/core/main.py
=> Create the image cache directory only when needed and always if needed

ranger/config/rifle.conf
- Terminal emulator and version: Terminator
- Python version: 3.7.2
- Locale: en_GB
Fix syntax in rifle.conf.
There wasn't any option to preview fonts before.
=> Rifle fixup

Makefile, ranger/api/commands.py, ranger/ext/direction.py, ranger/ext/human_readable.py, ranger/ext/iter_tools.py, ranger/ext/keybinding_parser.py, ranger/ext/lazy_property.py, ranger/ext/rifle.py, ranger/ext/signals.py, ranger/ext/widestring.py, ranger/gui/ansi.py, ranger/gui/widgets/console.py
=> Fix our doctests

ranger/config/rifle.conf
- Operating system and version: `Linux arch 4.20.4.a-1-hardened #1 SMP PREEMPT Fri Jan 25 01:24:51 CET 2019 x86_64 GNU/Linux`
- Terminal emulator and version: `termite v14`
- Python version: `Python 3.7.2`
- Ranger version/commit: `ranger 1.9.2`
- Locale: `en_US.UTF-8`
By default rifle does not use `imv` if it is installed. Adding it to the default config should fix the issue.
Considerations for `imv` have been included elsewhere so why not use it if it's available?
=> add imv to rifle.conf

HACKING.md
browserview.py -> view_miller.py
- Documentation Change
- [] Changes require config files to be updated
The file view_miller.py was referenced under an old name, browserview.py.
It is easier for someone trying to get into ranger development if the files one is supposed to read to get to know the code base exist. Hence they should reflect the actual file names.
`make test` has failed with errors I can't attribute to my change, but they also seem to occur on master (commit 2799318)
[make_test.txt](https://github.com/ranger/ranger/files/2985311/make_test.txt)
=> update HACKING.md with changed file name

ranger/core/actions.py
Couple extra changes in line with the argument swap for `tag`.
=> Expand on Vifon's tag_toggle argument swap

ranger/core/actions.py, ranger/ext/rifle.py
- Bug fix
- Terminal emulator and version: urxvt v9.22
- Python version: 3.7.0
- Ranger version/commit: ranger-master 1.9.2
Do not include "ask" in open_with options, since that option does nothing there and is redundant.
https://github.com/ranger/ranger/issues/1047
Tested with Python 2 and 3.
=> Do not include "ask" in open_with options (fixes #1047)

ranger/data/scope.sh
Scope now treats image/svg the same as image/svg+xml
=> Some SVG have MIME type image/svg

HACKING.md
Fixed spelling of 'relevant' (was relevand).
Changes fix a spelling issue.
---
---
=> [doc-issue] Fix spelling in Patching section

ranger/container/settings.py
now _setlocal_ works with directories whose name has regex metachars.
=> fixes #1566

README.md
This section was incomplete because `scope.sh` has grown a lot.
Fixes #1611
=> Improve the Dependencies section of the README

doc/ranger.1, doc/ranger.pod
=> Document tab_shift keybindings

doc/ranger.1, doc/ranger.pod
Shame on us, we didn't add any docs.
=> Document :trash command

ranger/core/runner.py, ranger/ext/rifle.py
Merged the wayland PR without checking CI status, I guess.
=> Fix long lines for pylint

ranger/gui/ui.py
See https://github.com/ranger/ranger/issues/1367
I'm not sure if this is the preferred way to exit ranger, suggestions welcome
=> Exit if STDIN is closed #1367

examples/fish_automatic_cd.fish
Simple alias to port the automatic_cd example to fish shell, fix #960 
=> port automatic_cd to fish, fix #960

ranger/data/mime.types
Some changes in the interest of ergonomics.
=> Refine custom mime types for rifle

ranger/data/scope.sh
- Operating system and version: 5.1.5-arch1-2-ARCH
- Terminal emulator and version: rxvt-unicode 9.22-7
- Python version: 3.7.3-1
- Ranger version/commit: 1.9.2-1
- Locale: 
LANG=en_CA.UTF-8
LC_CTYPE=en_CA.UTF-8
LC_NUMERIC="en_CA.UTF-8"
LC_TIME=en_DK.UTF-8
LC_COLLATE=C
LC_MONETARY="en_CA.UTF-8"
LC_MESSAGES="en_CA.UTF-8"
LC_PAPER="en_CA.UTF-8"
LC_NAME="en_CA.UTF-8"
LC_ADDRESS="en_CA.UTF-8"
LC_TELEPHONE="en_CA.UTF-8"
LC_MEASUREMENT="en_CA.UTF-8"
LC_IDENTIFICATION="en_CA.UTF-8"
LC_ALL=
I don't know how to preform tests. I am not a software developer :slightly_frowning_face: 
The title says it all.
Not required. Add functionality.
Office GUI take a long time to open. Having access to a preview of the file without having to open it in an external program …
=> Add preview support for .rtf, .doc, .docx, .xlsx, .xls in scope.sh

ranger/colorschemes/jungle.py
- Locale: 
The `progress_bar_color` was not used.
=> Remove duplicate code

ranger/config/rifle.conf
=> xdg-open is not compatible with the -- convention

doc/ranger.1, doc/ranger.pod
=> Refer to the correct environment variable for selecting a theme for bat

ranger/config/rc.conf
a little clean up. Possible values of viewmode are showed in comments above that option, so, it's not needed to make commented duplicate of this option.
- Improvement
=> extra comment is deleted

ranger/core/actions.py, ranger/ext/macrodict.py
While parsing the settings in `rc.conf` `self.fm.thisfile` doesn't exist
yet.
=> Catch exceptions when resolving macros in rc.conf

ranger/gui/widgets/console.py
😬  This causes crashes whenever the code paths come up.
=> Missed a couple py3 version checks

.pylintrc, ranger/config/.pylintrc, ranger/config/commands.py, ranger/container/settings.py, ranger/gui/color.py, tests/pylint/test_py2_compat.py
Because of pylint updates and some oversights on my part CI is currently borked. This should set that right.
=> Fix travis

Makefile
Tired of squinting at `make test` output.
=> Pretty make

ranger/data/scope.sh
- Operating system and version: 1.9.3-3
- Terminal emulator and version: st 0.8.4
- Python version: 1.9.3-3
- Ranger version/commit: 1.9.3-3
- Locale: 
LANG=en_CA.UTF-8
LC_CTYPE="en_CA.UTF-8"
LC_NUMERIC="en_CA.UTF-8"
LC_TIME=en_DK.UTF-8
LC_COLLATE=C
LC_MONETARY="en_CA.UTF-8"
LC_MESSAGES="en_CA.UTF-8"
LC_PAPER="en_CA.UTF-8"
LC_NAME="en_CA.UTF-8"
LC_ADDRESS="en_CA.UTF-8"
LC_TELEPHONE="en_CA.UTF-8"
LC_MEASUREMENT="en_CA.UTF-8"
LC_IDENTIFICATION="en_CA.UTF-8"
LC_ALL=
Add .ipynb extension to the JSON section of scope.sh otherwise Jupyter notebooks (json files with extension .ipynb) don't get any preview.
=> scope.sh: Add ipynb extension to JSON section to get preview of Jupyter notebooks

.github/workflows/shellcheck.yml
The shellcheck download URL changed.
=> Fix shellcheck download url

ranger/config/commands_sample.py
- N/A
Fixed typo in comments for commands_sample.py:  "acitons" -> "actions"
Fix typo
None, only single line comment change
=> Fix comment typo in commands_sample.py

ranger/ext/vcs/git.py
- Bug fix
- Operating system and version: WSL2 (Win10)
- Ranger version: ranger 1.9.3
- Python version: 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
Support git hierarchical branch names (include forward slashes in git branch names)
Resolves https://github.com/ranger/ranger/issues/2311
Tested locally with my existing workflow
=> fix(git): support hierarchical branch names

ranger/config/rifle.conf
adding rifle.conf
atril can open cbr,cbz too
mcomix can open rar, zip too, set to low priority, it's not an archive manager, it's a comic book viewer.
=> [minor] mcomix and atril update in rifle

README.md, doc/cheatsheet.svg, doc/ranger.1, doc/ranger.pod
Unfortunately there's no Libera.Chat webclient I can link to, so the
connecting guide'll have to do.
=> README: Update IRC channel information

ranger/container/tags.py
Fixes #2295
Co-authored-by: @chu4ng
You were right, @chu4ng, thanks for bringing it up! Next time feel free to just open a PR.
=> tags: Fix argument length checking

ranger/container/tags.py
- Bug fix
- Python version: 2.7.18 and 3.9.5
- Ranger version/commit: master / v1.9.3-232-g0d704c74
Seems like python2 has other error class handler for this issue, so I just added him.
#2388
=> Added IOError to error handler.

ranger/ext/img_display.py
=> img_display: Make the unsupported exception friendlier

ranger/__init__.py, ranger/config/commands.py, ranger/container/bookmarks.py, ranger/container/history.py, ranger/container/tags.py, ranger/core/actions.py, ranger/core/loader.py, ranger/core/main.py, ranger/core/runner.py, ranger/ext/accumulator.py, ranger/ext/img_display.py, ranger/ext/macrodict.py, ranger/ext/open23.py, ranger/ext/popen_forked.py, ranger/ext/rifle.py, ranger/ext/spawn.py, ranger/ext/vcs/vcs.py, ranger/gui/colorscheme.py, ranger/gui/widgets/console.py, tests/manpage_completion_test.py
This is gonna require significant testing. Time to push to prod^Wmaster!
=> Updating the code for a newer pylint

ranger/config/commands.py
- bugfix
using grep as provided by busybox in alpine linux
- Locale:
=> grep command: fix to work with busybox (and other Posix compliant implementations)grep

README.md, doc/ranger.1, doc/ranger.pod
Libera.Chat has a webchat now, let's link to it for the convenience of our users who aren't familiar with IRC.
=> Update README and man page with Libera webchat

doc/ranger.1, doc/ranger.pod
=> Fix deletion confirmation default indication

ranger/data/scope.sh
preview of the embedded images in audio files
It's a simple change in scope.sh,
=> thumbnail preview for audio

.github/workflows/pylint.yml, .github/workflows/python.yml, .pylintrc, doc/tools/convert_papermode_to_metadata.py, examples/plugin_ipc.py, ranger/config/.pylintrc, ranger/container/file.py, ranger/container/tags.py, ranger/core/actions.py, ranger/core/loader.py, ranger/core/runner.py, ranger/ext/img_display.py, ranger/ext/macrodict.py, ranger/ext/popen_forked.py, ranger/ext/rifle.py, ranger/ext/vcs/vcs.py, tests/manpage_completion_test.py, tests/pylint/py2_compat.py, tests/pylint/test_py2_compat.py
I made a mess of master by accident. Apparently all of the bad-option-value problems were because of the version of Pylint I used to determine which options to pass (WAT???).
=> Pylint: Fix the mess

Makefile, doc/ranger.1, doc/ranger.pod
Docs got some little discrepancies.
=> Openscad doc

ranger/core/fm.py
=> fm: Add nsxiv to sxiv workaround

.github/workflows/pylint.yml, .github/workflows/python.yml, .pylintrc, ranger/config/.pylintrc, ranger/container/bookmarks.py, ranger/container/directory.py, ranger/container/settings.py, ranger/core/actions.py, ranger/data/scope.sh, ranger/ext/img_display.py, ranger/ext/keybinding_parser.py, ranger/ext/vcs/vcs.py, ranger/gui/ui.py, ranger/gui/widgets/browsercolumn.py, ranger/gui/widgets/pager.py, requirements.txt, tests/pylint/py2_compat.py, tests/pylint/python3.py, tests/ranger/container/test_fsobject.py
GHActions refuses to install Python 3.5 now, oldest available seems to be 3.7 despite what's on their list.
=> GHActions: Only PyLint on latest and bump 3.5 to 3.7

ranger/ext/rifle.py
- Improvement
When I was running `ranger` in an embedded device (a NAS) with ssh, I was trying to edit something and it keeps refusing to open some files. After checking the log, I found the following:
```sh
Traceback (most recent call last):
File "/volume1/main/home/soraxas/git-repo/ranger/ranger/core/actions.py", line 271, in execute_console
cmd.execute()
File "/volume1/main/home/soraxas/git-repo/ranger/ranger/config/commands.py", line 1144, in execute
self.fm.execute_file([File(listpath)], app='editor')
File "/volume1/main/home/soraxas/git-repo/ranger/ranger/core/actions.py", line 465, in execute_file
return execute()
File "/volume1/main/home/soraxas/git-repo/ranger/ranger/core/actions.py", line 463, in execute
return self.rifle.execute(filenames, mode, label, flags, None)
File …
```
=> Gracefully fallback when file(1) is not available to identify mime-type

doc/ranger.pod
Modify w3m image preview doc to mention Alacritty and tmux support.
- Documentation
=> doc: w3m preview compatible with Alacritty and tmux

.github/workflows/python.yml
Apply the same fix for the setupterm issue as for the test_PR job.
=> GHActions: Set TERM for test_py job

.github/workflows/pr.yml, .github/workflows/pypy.yml, .github/workflows/python.yml, .github/workflows/shellcheck.yml, .pylintrc, ranger/container/history.py, ranger/core/actions.py, ranger/core/loader.py, ranger/core/main.py, ranger/core/runner.py, ranger/ext/direction.py, ranger/ext/img_display.py, ranger/ext/rifle.py, ranger/ext/shutil_generatorized.py, ranger/ext/signals.py, ranger/ext/vcs/vcs.py, ranger/gui/widgets/pager.py, requirements.txt, tests/pylint/py2_compat.py, tests/pylint/python3.py
This should make CI useful again.
=> Conform to updated Pylint

ranger/core/actions.py, ranger/core/runner.py
Trying to follow best practices relating to restricting the amount of positional arguments I've introduced errors by accident.
Fixes #3040
=> Fix positional argument calls

ranger/gui/widgets/view_base.py
This reverts commit 4031ee1564ab36fed1dfcb1c1e859a1d674ba007.
Fixes #3104
@dgshanee, what I was afraid of has come to pass. It'd be cool if you took another shot at fixing the issue.
=> Revert "fixed open_with bugginess"
